#!/bin/sh 

dir=/home/plank/cs302/Labs/Lab2
ge="$dir/Gradescript-Examples"

if [ $# -ne 0 ]; then
  echo 'usage: gradeall' >&2
  exit 1
fi

enum=1
n=0
while [ $enum -le 100 ]; do
  s1=`date | sed 's/.*\(..\):\(..\):\(..\).*/\1 \2 \3/' | awk '{ print $1*3600 + $2*60 + $3 }'`
  out=`$dir/gradescript $enum  | head -n 1`
  s2=`date | sed 's/.*\(..\):\(..\):\(..\).*/\1 \2 \3/' | awk '{ print $1*3600 + $2*60 + $3 }'`
  diff=`echo $s1 $s2 | awk '{ print $2-$1 }'`
  if [ $diff -lt 0 ]; then
    diff=`echo $diff | awk '{ print $1 + 3600*24 }'`
  fi
  echo $out "Seconds = " $diff
  n=`echo $n $out | awk '{ print $1 + ($NF == "correct.") }'`

  rm -f tmp-???-test-stdout.txt tmp-???-test-stderr.txt tmp-???-correct-stdout.txt tmp-???-correct-stderr.txt

  enum=`echo $enum | awk '{ print $1+1 }'`
done

echo ""

echo "$n Correct out of 100"
