/home/plank/cs360/labs/lab5/Gradescript-Examples/mrd 95 13 6 d 26 your-dir
/home/plank/cs360/labs/lab5/Gradescript-Examples/jtlaunch c > tarfile
mv your-dir test-dir
/home/plank/cs360/labs/lab5/Gradescript-Examples/jtlaunch x < tarfile

if [ ! -d your-dir ]; then
  echo 'Your tar x command did not create the directory your-dir.' >&2
  exit 1
fi

/home/plank/cs360/labs/lab5/tar-checker test-dir your-dir c t p l
