#include <fstream>
#include <algorithm>
#include <iostream>
#include <sstream>
#include <cstdio>
#include <cstdlib>
#include <vector>
using namespace std;

typedef vector <string> SVec;
typedef vector <SVec> SSVec;

#define VIT(i, v) for (i = 0; i < v.size(); i++)
#define IT(it, ds) for (it = ds.begin(); it != ds.end(); it++)
#define FUP(i, n) for (i = 0; i < n; i++)

#define O1(v) cout << v << endl
#define O2(v1, v2) cout << v1 << " " << v2 << endl
#define O3(v1, v2, v3) cout << v1 << " " << v2 << " " << v3 << endl
#define OVEC(v) { int iii; VIT(iii, v) cout << v[iii] << " " ; cout << endl; }
typedef vector <double> DVec;

const char *lns[7908] = { "Aarhus", "Abacus", "Abalone", "Abandon", "Abater", "Abbott",
"Abdomen", "Abduct", "Abelian", "Abelson", "Abetted", "Abeyant",
"Abidjan", "Abigail", "Abject", "Ablate", "Ablaze", "Aboard",
"Abolish", "Abound", "Abrade", "Abraham", "Abreact", "Abreast",
"Abridge", "Abroad", "Abrupt", "Abscess", "Absence", "Absent",
"Absolve", "Absorb", "Abstain", "Absurd", "Abusive", "Abutted",
"Abysmal", "Academe", "Academy", "Acadia", "Accede", "Accent",
"Accept", "Access", "Acclaim", "Accord", "Accost", "Account",
"Accrual", "Accrue", "Accuse", "Acerbic", "Acetate", "Acetic",
"Acetone", "Achieve", "Aching", "Acidic", "Ackley", "Acolyte",
"Acquire", "Acquit", "Acreage", "Acrobat", "Acronym", "Across",
"Acrylic", "Actaeon", "Actinic", "Actress", "Actual", "Actuate",
"Acuity", "Acumen", "Acyclic", "Adagio", "Adamant", "Adamson",
"Addend", "Addenda", "Addict", "Addison", "Address", "Adduce",
"Adelia", "Adenine", "Adenoma", "Adhere", "Adipic", "Adject",
"Adjoin", "Adjoint", "Adjourn", "Adjudge", "Adjunct", "Adjust",
"Adkins", "Admiral", "Admire", "Adolph", "Adonis", "Adrenal",
"Adrian", "Adrift", "Adroit", "Adsorb", "Adulate", "Advance",
"Advent", "Adverb", "Adverse", "Advert", "Advice", "Advise",
"Advisee", "Advisor", "Aegean", "Aeneas", "Aeneid", "Aeolian",
"Aeolus", "Aerate", "Aerial", "Aerobic", "Aerosol", "Affable",
"Affair", "Affect", "Affine", "Affirm", "Afflict", "Afford",
"Affront", "Afghan", "Afield", "Aflame", "Afloat", "Afraid",
"Afresh", "Africa", "Against", "Agatha", "Agenda", "Aghast",
"Agitate", "Agleam", "Agnomen", "Agouti", "Agreed", "Aileen",
"Aileron", "Airdrop", "Airfare", "Airflow", "Airfoil", "Airlift",
"Airline", "Airlock", "Airmail", "Airman", "Airmass", "Airmen",
"Airpark", "Airport", "Airway", "Aitken", "Alabama", "Alameda",
"Alaska", "Albania", "Albany", "Albeit", "Albert", "Alberta",
"Alberto", "Albumin", "Alchemy", "Alcmena", "Alcohol", "Alcott",
"Alcove", "Aldrich", "Aldrin", "Alewife", "Alexei", "Alexis",
"Alfalfa", "Alfonso", "Alfonso", "Alfred", "Alfredo", "Algebra",
"Algenib", "Algeria", "Algiers", "Alicia", "Alight", "Alimony",
"Aliquot", "Alison", "Alkali", "Alkane", "Alkene", "Allege",
"Allegra", "Allegro", "Allele", "Allergy", "Allied", "Allison",
"Allude", "Allure", "Almaden", "Almanac", "Almond", "Almost",
"Alpert", "Alpine", "Already", "Altair", "Altern", "Althea",
"Alumina", "Alumna", "Alumnae", "Alumni", "Alumnus", "Alundum",
"Alvarez", "Alveoli", "Always", "Alyssum", "Amadeus", "Amalgam",
"Amanita", "Amateur", "Amatory", "Amazon", "Ambient", "Ambling",
"Ambrose", "Ambush", "Amelia", "Amende", "Amerada", "America",
"Ameslan", "Amherst", "Amidst", "Ammeter", "Ammonia", "Amnesia",
"Amoeba", "Amoebae", "Amongst", "Amoral", "Amorous", "Amount",
"Ampere", "Amplify", "Amputee", "Amtrak", "Amulet", "Anabel",
"Anagram", "Anaheim", "Analogy", "Analyst", "Anarch", "Anarchy",
"Anatole", "Anatomy", "Anchor", "Anchovy", "Ancient", "Andean",
"Andiron", "Andorra", "Andover", "Andrea", "Andrei", "Andrew",
"Andrews", "Anemone", "Angela", "Angeles", "Angelic", "Angelo",
"Angles", "Angling", "Angola", "Angora", "Anguish", "Angular",
"Aniline", "Animal", "Animate", "Animism", "Anionic", "Ankara",
"Annale", "Annalen", "Annals", "Anneal", "Annette", "Annual",
"Annuity", "Annular", "Annuli", "Annulus", "Anodic", "Anomaly",
"Anomie", "Another", "Anselm", "Anselmo", "Answer", "Antacid",
"Antaeus", "Antares", "Antenna", "Anthem", "Anther", "Anthony",
"Antigen", "Antioch", "Antique", "Antler", "Antoine", "Antonio",
"Antony", "Antonym", "Antwerp", "Anxiety", "Anxious", "Anybody",
"Anyhow", "Anyone", "Anyway", "Apache", "Apathy", "Apatite",
"Aphasia", "Aphasic", "Apices", "Apiece", "Aplomb", "Apogee",
"Apollo", "Apology", "Apostle", "Appall", "Apparel", "Appeal",
"Appear", "Appease", "Append", "Appian", "Applaud", "Appleby",
"Applied", "Appoint", "Apport", "Apprise", "Approve", "Apricot",
"Apropos", "Aquatic", "Aqueous", "Aquila", "Aquinas", "Arabia",
"Arabic", "Arachne", "Arbiter", "Arbutus", "Arcade", "Arcadia",
"Arcana", "Arcane", "Arccos", "Archae", "Archaic", "Archer",
"Archery", "Arching", "Archive", "Arcing", "Arcsin", "Arcsine",
"Arctan", "Arctic", "Ardency", "Ardent", "Arduous", "Areaway",
"Argive", "Argonne", "Ariadne", "Arisen", "Arizona", "Arlene",
"Armada", "Armata", "Armenia", "Armful", "Armhole", "Armload",
"Armoire", "Armonk", "Armour", "Armpit", "Arnold", "Around",
"Arousal", "Arouse", "Arrack", "Arragon", "Arraign", "Arrange",
"Arrear", "Arrest", "Arrival", "Arrive", "Arroyo", "Arsenal",
"Arsenic", "Arsine", "Artemis", "Artery", "Artful", "Arthur",
"Article", "Artisan", "Arturo", "Artwork", "Ascend", "Ascent",
"Ascetic", "Ascribe", "Aseptic", "Asexual", "Ashame", "Ashamed",
"Ashland", "Ashley", "Ashman", "Ashmen", "Ashore", "Ashtray",
"Asiatic", "Asinine", "Askance", "Asleep", "Asocial", "Aspect",
"Asphalt", "Aspire", "Aspirin", "Assail", "Assault", "Assent",
"Assert", "Assess", "Assign", "Assist", "Assort", "Assuage",
"Assume", "Assure", "Assyria", "Astarte", "Asteria", "Asthma",
"Astoria", "Astound", "Astral", "Astray", "Astride", "Astute",
"Asunder", "Asylum", "Atavism", "Atheism", "Atheist", "Athena",
"Athens", "Athlete", "Athwart", "Atkins", "Atlanta", "Atomic",
"Atonal", "Atreus", "Atrium", "Atrophy", "Atropos", "Attach",
"Attache", "Attack", "Attain", "Attempt", "Attend", "Attest",
"Attica", "Attire", "Attract", "Attune", "Atwater", "Atwood",
"Atypic", "Auberge", "Aubrey", "Auburn", "Auction", "Audible",
"Auditor", "Audrey", "Audubon", "Augean", "Augend", "Augite",
"Augment", "August", "Augusta", "Auntie", "Auriga", "Aurochs",
"Aurora", "Austere", "Austin", "Austria", "Author", "Autism",
"Automat", "Autopsy", "Autumn", "Avarice", "Avenge", "Avenue",
"Average", "Averred", "Averse", "Avesta", "Aviary", "Aviate",
"Avionic", "Avocado", "Avocate", "Avocet", "Avowal", "Awaken",
"Awesome", "Awhile", "Awkward", "Axolotl", "Azalea", "Azimuth",
"Aztecan", "Babbitt", "Babble", "Babcock", "Baboon", "Babylon",
"Babysat", "Babysit", "Bacchus", "Bacilli", "Backlog", "Backup",
"Badland", "Baffin", "Baffle", "Baggage", "Bagging", "Baghdad",
"Bagley", "Bagpipe", "Bahama", "Bahrein", "Bailey", "Bailiff",
"Bainite", "Bakery", "Baklava", "Balance", "Balboa", "Balcony",
"Baldwin", "Baleen", "Baleful", "Balfour", "Balkan", "Ballad",
"Ballard", "Ballast", "Balled", "Ballet", "Balloon", "Ballot",
"Balsam", "Baltic", "Balzac", "Bamako", "Bamboo", "Banach", "Banana",
"Banbury", "Bandage", "Bandgap", "Bandit", "Baneful", "Bangkok",
"Bangle", "Bangor", "Bangui", "Banish", "Banquet", "Banshee",
"Bantam", "Banter", "Bantus", "Baptism", "Baptist", "Barbara",
"Barbell", "Barber", "Barbour", "Barbudo", "Barclay", "Barfly",
"Bargain", "Barium", "Barkeep", "Barley", "Barlow", "Barnard",
"Barnes", "Barnet", "Barnett", "Barney", "Baronet", "Barony",
"Baroque", "Barrack", "Barrage", "Barrel", "Barren", "Barrett",
"Barrier", "Barrow", "Barstow", "Bartend", "Barter", "Bartok",
"Barton", "Basalt", "Baseman", "Basemen", "Bashaw", "Bashful",
"Basilar", "Basket", "Bassett", "Bastard", "Bastion", "Batavia",
"Bateau", "Bateman", "Bathos", "Bathtub", "Batten", "Battery",
"Battle", "Batwing", "Bauble", "Bauhaus", "Bausch", "Bauxite",
"Bavaria", "Baxter", "Baylor", "Bayonet", "Bayonne", "Bayport",
"Bazaar", "Beacon", "Beadle", "Bearish", "Beastie", "Beaten",
"Beater", "Beatify", "Beatnik", "Beauty", "Beaver", "Becalm",
"Became", "Because", "Bechtel", "Becker", "Becket", "Beckman",
"Beckon", "Becloud", "Become", "Bedbug", "Bedevil", "Bedfast",
"Bedford", "Bedlam", "Bedpost", "Bedrock", "Bedroom", "Bedside",
"Bedtime", "Beecham", "Beehive", "Beetle", "Befall", "Befell",
"Before", "Befoul", "Beggar", "Beggary", "Begging", "Begonia",
"Beguile", "Behalf", "Behave", "Behead", "Beheld", "Behest",
"Behind", "Behold", "Beijing", "Beirut", "Belate", "Belfast",
"Belfry", "Belgian", "Belgium", "Belief", "Belies", "Believe",
"Bellamy", "Bellboy", "Bellhop", "Bellini", "Bellman", "Bellmen",
"Bellow", "Bellum", "Belmont", "Beloit", "Belong", "Belove",
"Belying", "Bemoan", "Bemuse", "Bender", "Bendix", "Beneath",
"Benefit", "Benelux", "Bengal", "Bengali", "Benight", "Benign",
"Bennett", "Benson", "Bentham", "Benthic", "Bentley", "Benton",
"Benzene", "Beograd", "Beowulf", "Bequest", "Berate", "Bereave",
"Bereft", "Bergen", "Bergman", "Bergson", "Berlin", "Berlioz",
"Berlitz", "Berman", "Bermuda", "Bernard", "Bernet", "Bernice",
"Bernie", "Bernini", "Berserk", "Bertha", "Bertie", "Bertram",
"Berwick", "Beseech", "Beside", "Besiege", "Bespeak", "Bespoke",
"Bessel", "Bessie", "Bestial", "Bestir", "Bestow", "Bethel",
"Betide", "Betoken", "Betony", "Betray", "Betroth", "Betsey",
"Bettor", "Between", "Betwixt", "Beverly", "Bewail", "Beware",
"Bewitch", "Beyond", "Bhutan", "Bianco", "Biaxial", "Biceps",
"Bicker", "Bicycle", "Bidden", "Bifocal", "Bigelow", "Bigotry",
"Bikini", "Bilayer", "Billet", "Billie", "Billion", "Billow",
"Bimini", "Bimodal", "Binary", "Bindery", "Bindle", "Bingham",
"Bingle", "Biology", "Biopsy", "Biotic", "Biotite", "Biplane",
"Bipolar", "Birdie", "Birgit", "Biscuit", "Bisect", "Bishop",
"Bismark", "Bismuth", "Bisque", "Bissau", "Bistate", "Bitnet",
"Bitten", "Bittern", "Bitumen", "Bitwise", "Bivalve", "Bivouac",
"Bizarre", "Blacken", "Bladder", "Blaine", "Blanch", "Blanche",
"Blanket", "Blatant", "Blather", "Blazon", "Bleach", "Bleary",
"Bleeker", "Blemish", "Blight", "Blister", "Blithe", "Blocky",
"Blonde", "Bloody", "Blossom", "Blotch", "Blouse", "Blowup",
"Blubber", "Bluish", "Blunder", "Blurry", "Bluster", "Blythe",
"Boatman", "Boatmen", "Bobbie", "Bobbin", "Bobble", "Bobcat",
"Bodice", "Bodied", "Boeing", "Boeotia", "Bogging", "Boggle",
"Bogota", "Bohemia", "Boletus", "Bolivar", "Bolivia", "Bologna",
"Bolshoi", "Bolster", "Bolton", "Bombard", "Bombast", "Bombay",
"Bonanza", "Bondage", "Bonfire", "Bonito", "Bonnet", "Bonnie",
"Boogie", "Bookend", "Bookie", "Bookish", "Booklet", "Boolean",
"Boorish", "Bootes", "Bootleg", "Borate", "Borden", "Border",
"Boreas", "Boredom", "Borneo", "Borough", "Borrow", "Bosonic",
"Boston", "Boswell", "Botanic", "Botany", "Botfly", "Bottle",
"Bottom", "Botulin", "Boucher", "Bought", "Boulder", "Bounce",
"Bouncy", "Bounty", "Bouquet", "Bourbon", "Bovine", "Bowdoin",
"Bowfin", "Bowline", "Bowman", "Bowmen", "Boxcar", "Boxwood",
"Boycott", "Boyhood", "Boyish", "Bracken", "Bracket", "Bradley",
"Brahms", "Braille", "Brainy", "Bramble", "Branch", "Brandon",
"Brandt", "Brandy", "Braniff", "Brassy", "Bravado", "Bravery",
"Bravura", "Brazen", "Brazier", "Brazil", "Breach", "Breadth",
"Breakup", "Breast", "Breath", "Breathe", "Breathy", "Breccia",
"Breech", "Breeze", "Breezy", "Bremen", "Brenda", "Brendan",
"Brennan", "Brenner", "Breton", "Brevet", "Brevity", "Brewery",
"Bribery", "Bridal", "Bridge", "Bridget", "Bridle", "Brigade",
"Briggs", "Brigham", "Bright", "Brimful", "Brindle", "Bristle",
"Bristol", "Britain", "British", "Briton", "Britten", "Brittle",
"Broach", "Broaden", "Brocade", "Brockle", "Broglie", "Broken",
"Bromide", "Bromine", "Bromley", "Bronchi", "Bronco", "Bronze",
"Bronzy", "Broody", "Brooke", "Brothel", "Brother", "Brought",
"Browne", "Brownie", "Browse", "Bruegel", "Bruise", "Brumidi",
"Brunch", "Brushy", "Brusque", "Brutal", "Bryant", "Bryozoa",
"Bubble", "Bucket", "Buckeye", "Buckle", "Buckley", "Bucolic",
"Buddha", "Budget", "Buenos", "Buffalo", "Buffet", "Buffoon",
"Bugaboo", "Bugeyed", "Bugging", "Buildup", "Builtin", "Bulblet",
"Bulldog", "Bullet", "Bullish", "Bullock", "Bulrush", "Bulwark",
"Bumble", "Bundle", "Bungle", "Bunsen", "Bunyan", "Buoyant",
"Burbank", "Burden", "Burdock", "Bureau", "Burette", "Burgeon",
"Burgess", "Burgher", "Burglar", "Burial", "Buried", "Burlap",
"Burley", "Burmese", "Burnett", "Burnham", "Burnish", "Burnout",
"Burrow", "Bursty", "Burton", "Burundi", "Busboy", "Bushel",
"Bustard", "Bustle", "Butane", "Butene", "Butler", "Buttery",
"Buttock", "Button", "Butyric", "Buxton", "Buzzard", "Buzzer",
"Buzzing", "Buzzsaw", "Bygone", "Byline", "Bypass", "Bypath",
"Byroad", "Byronic", "Byword", "Cabana", "Cabaret", "Cabbage",
"Cabinet", "Cackle", "Cactus", "Cadaver", "Caddis", "Cadent",
"Cadenza", "Cadmium", "Caesar", "Cahill", "Cahoot", "Caiman",
"Cajole", "Calais", "Calamus", "Calcify", "Calcine", "Calcite",
"Calcium", "Calculi", "Calder", "Caldera", "Calgary", "Calhoun",
"Caliber", "Calibre", "Calico", "Caliper", "Caliph", "Calkins",
"Caller", "Callous", "Callus", "Caloric", "Calorie", "Calumet",
"Calumny", "Calvary", "Calvert", "Calvin", "Calypso", "Camber",
"Cambric", "Camden", "Camelot", "Camera", "Cameron", "Camilla",
"Camilla", "Camille", "Camino", "Campion", "Campus", "Canaan",
"Canada", "Canary", "Cancel", "Cancer", "Candace", "Candela",
"Candid", "Candide", "Candle", "Canine", "Canker", "Cannel",
"Cannery", "Cannon", "Cannot", "Canoga", "Canonic", "Canopy",
"Canteen", "Cantle", "Canton", "Cantor", "Canvas", "Canvass",
"Canyon", "Capella", "Capita", "Capital", "Capitol", "Caprice",
"Capsize", "Capstan", "Capsule", "Captain", "Caption", "Captive",
"Captor", "Capture", "Caputo", "Carabao", "Caracas", "Caramel",
"Caravan", "Caraway", "Carbide", "Carbine", "Carbon", "Carbone",
"Carboxy", "Carboy", "Carcass", "Cardiac", "Cardiff", "Cardiod",
"Careen", "Career", "Careful", "Caress", "Carfare", "Cargill",
"Cargoes", "Caribou", "Carlin", "Carload", "Carlson", "Carlton",
"Carlyle", "Carmela", "Carmen", "Carmine", "Carnage", "Carnal",
"Carney", "Carolyn", "Carouse", "Carpet", "Carport", "Carrara",
"Carrel", "Carrie", "Carrion", "Carroll", "Carrot", "Carson",
"Cartel", "Carton", "Cartoon", "Caruso", "Carven", "Casbah",
"Cascade", "Cascara", "Casein", "Cashew", "Cashier", "Casino",
"Casket", "Caspian", "Cassius", "Cassock", "Casteth", "Castle",
"Castor", "Castro", "Casual", "Catalpa", "Catawba", "Catbird",
"Catcall", "Catchup", "Catchy", "Catfish", "Cathode", "Cation",
"Catkin", "Catlike", "Catnip", "Catsup", "Cattail", "Cattle",
"Cauchy", "Caucus", "Caught", "Causal", "Causate", "Caustic",
"Caution", "Cavalry", "Caveat", "Caveman", "Cavemen", "Cavern",
"Caviar", "Cavort", "Cayenne", "Cayley", "Cayuga", "Cecilia",
"Cedilla", "Cedric", "Celebes", "Celery", "Celesta", "Celeste",
"Cellar", "Celsius", "Celtic", "Cement", "Censor", "Censure",
"Census", "Centaur", "Central", "Centrex", "Centric", "Centum",
"Century", "Cepheus", "Ceramic", "Cereal", "Cereus", "Cerise",
"Cerium", "Certain", "Certify", "Cervix", "Cesare", "Cesium",
"Cession", "Cessna", "Cetera", "Ceylon", "Cezanne", "Chablis",
"Chagrin", "Chaise", "Chalet", "Chalice", "Chalky", "Chamber",
"Chamfer", "Chamois", "Chance", "Chancel", "Chancy", "Change",
"Channel", "Chanson", "Chantey", "Chantry", "Chaotic", "Chapel",
"Chaplin", "Chapman", "Chapter", "Charge", "Chariot", "Charity",
"Charles", "Charley", "Charlie", "Charon", "Charta", "Chassis",
"Chaste", "Chateau", "Chatham", "Chattel", "Chatty", "Chaucer",
"Cheater", "Checkup", "Cheeky", "Cheery", "Cheese", "Cheesy",
"Cheetah", "Chelate", "Chemic", "Chemise", "Chemist", "Cheney",
"Cherish", "Cherry", "Cherub", "Cheryl", "Chester", "Chevron",
"Chiang", "Chianti", "Chicago", "Chicano", "Chicken", "Chicory",
"Chiffon", "Chigger", "Chignon", "Chilean", "Chilly", "Chimera",
"Chimney", "Chinch", "Chinese", "Chinook", "Chisel", "Chiton",
"Choctaw", "Choice", "Cholera", "Chomsky", "Choose", "Choosy",
"Chopin", "Choppy", "Choral", "Chorale", "Chordal", "Chorine",
"Chortle", "Chorus", "Chosen", "Chowder", "Christ", "Christy",
"Chrome", "Chromic", "Chronic", "Chubby", "Chuckle", "Chummy",
"Chunky", "Church", "Chutney", "Cicada", "Cicero", "Ciliate",
"Cinder", "Cinema", "Cipher", "Circle", "Circlet", "Circuit",
"Circus", "Cistern", "Citadel", "Citizen", "Citrate", "Citric",
"Citroen", "Citron", "Citrus", "Claire", "Clamber", "Clammy",
"Claret", "Clarify", "Clarity", "Clarke", "Classic", "Classy",
"Clatter", "Claude", "Claudia", "Claudio", "Clause", "Clausen",
"Clayton", "Cleanse", "Cleanup", "Cleave", "Clement", "Clemson",
"Clench", "Clergy", "Cleric", "Clever", "Cliche", "Client",
"Clifton", "Climate", "Climax", "Clinch", "Clinic", "Clinton",
"Clique", "Clobber", "Clonic", "Closet", "Closeup", "Closure",
"Clothe", "Clotho", "Cloture", "Cloudy", "Cloven", "Clumsy",
"Cluster", "Clutch", "Clutter", "Coarse", "Coarsen", "Coastal",
"Coates", "Coaxial", "Cobalt", "Cobble", "Cobweb", "Cocaine",
"Cochlea", "Cochran", "Cockeye", "Cockle", "Cockpit", "Coconut",
"Cocoon", "Coddle", "Codfish", "Codicil", "Codify", "Coequal",
"Coerce", "Coexist", "Coffee", "Coffer", "Coffey", "Coffin",
"Coffman", "Cogent", "Cognac", "Cognate", "Cohere", "Cohort",
"Cohosh", "Coinage", "Coleman", "Colette", "Coleus", "Colgate",
"Colicky", "Collage", "Collar", "Collard", "Collate", "Collect",
"College", "Collet", "Collide", "Collie", "Collier", "Collins",
"Colloq", "Collude", "Cologne", "Colombo", "Colonel", "Colony",
"Colossi", "Coltish", "Column", "Combat", "Combine", "Comedy",
"Cometh", "Comfort", "Command", "Commend", "Comment", "Commit",
"Common", "Commune", "Commute", "Compact", "Company", "Compare",
"Compass", "Compel", "Compete", "Compile", "Complex", "Comply",
"Comport", "Compose", "Compost", "Compote", "Compton", "Compute",
"Comrade", "Conakry", "Conant", "Concave", "Conceal", "Concede",
"Conceit", "Concept", "Concern", "Concert", "Concise", "Concoct",
"Concord", "Concur", "Condemn", "Condone", "Conduce", "Conduct",
"Conduit", "Confect", "Confer", "Confess", "Confide", "Confine",
"Confirm", "Conform", "Confuse", "Confute", "Congeal", "Congest",
"Conifer", "Conjoin", "Conjure", "Conklin", "Conley", "Connect",
"Conner", "Connie", "Connive", "Connors", "Connote", "Conquer",
"Conrad", "Conrail", "Consent", "Consign", "Consist", "Console",
"Consort", "Consul", "Consult", "Consume", "Contact", "Contain",
"Contend", "Content", "Contest", "Context", "Contort", "Contour",
"Control", "Convair", "Convect", "Convene", "Convent", "Convert",
"Convex", "Convey", "Convict", "Convoke", "Convoy", "Conway",
"Cookery", "Cookie", "Coolant", "Cooley", "Copious", "Coppery",
"Copter", "Coquina", "Corbel", "Corbett", "Cordage", "Cordial",
"Cordite", "Cordon", "Corinth", "Cornea", "Cornell", "Cornet",
"Cornish", "Cornish", "Corona", "Coroner", "Coronet", "Corpora",
"Corpse", "Corpus", "Corral", "Correct", "Corrode", "Corrupt",
"Corsage", "Corset", "Cortege", "Cortex", "Corvus", "Cosine",
"Cosmic", "Cosmos", "Cossack", "Costume", "Cotman", "Cottage",
"Cotton", "Cottony", "Cougar", "Coulomb", "Coulter", "Council",
"Counsel", "Country", "County", "Couple", "Coupon", "Courage",
"Courier", "Course", "Cousin", "Covary", "Covert", "Coward",
"Cowbell", "Cowbird", "Cowboy", "Cowgirl", "Cowhand", "Cowherd",
"Cowhide", "Cowlick", "Cowman", "Cowmen", "Cowpea", "Cowpoke",
"Cowpony", "Cowpox", "Cowslip", "Coxcomb", "Coyote", "Crackle",
"Cradle", "Crafty", "Craggy", "Cramer", "Crania", "Cranium",
"Cranky", "Cranny", "Crappie", "Crater", "Cravat", "Craven",
"Crayon", "Creaky", "Creamy", "Crease", "Create", "Creche",
"Credent", "Credit", "Creedal", "Creepy", "Cremate", "Creole",
"Cretan", "Cretin", "Crevice", "Crewcut", "Crewel", "Crewman",
"Crewmen", "Cricket", "Crimea", "Crimson", "Cringe", "Crinkle",
"Cripple", "Crises", "Crisis", "Crispin", "Critic", "Critter",
"Croatia", "Crochet", "Crocus", "Croquet", "Crosby", "Crotch",
"Crouch", "Crowley", "Croydon", "Crucial", "Crucify", "Cruddy",
"Cruelty", "Cruise", "Crumble", "Crummy", "Crumple", "Crunch",
"Crupper", "Crusade", "Crusoe", "Crusty", "Crutch", "Cryptic",
"Crystal", "Cuckoo", "Cuddle", "Cuddly", "Cudgel", "Cuisine",
"Culprit", "Culture", "Culver", "Culvert", "Cummins", "Cumulus",
"Cunard", "Cunning", "Cupful", "Cupric", "Cuprous", "Curate",
"Curdle", "Curfew", "Curious", "Curium", "Curlew", "Curran",
"Currant", "Current", "Cursive", "Cursor", "Cursory", "Curtail",
"Curtain", "Curtis", "Curtsey", "Cushing", "Cushion", "Cushman",
"Custer", "Custody", "Custom", "Cutback", "Cutesy", "Cutlass",
"Cutler", "Cutlet", "Cutoff", "Cutout", "Cutover", "Cutset",
"Cutworm", "Cyanate", "Cyanic", "Cyanide", "Cyclic", "Cyclist",
"Cyclone", "Cyclops", "Cygnus", "Cynthia", "Cypress", "Cyprian",
"Cypriot", "Cyprus", "Czarina", "Dabble", "Dactyl", "Dadaism",
"Dadaist", "Dagger", "Dahlia", "Dahomey", "Dailey", "Daimler",
"Dainty", "Dakota", "Dallas", "Dalton", "Dalzell", "Damage",
"Damask", "Dampen", "Damsel", "Danbury", "Danger", "Dangle",
"Daniel", "Danish", "Danube", "Danzig", "Daphne", "Dapper", "Dapple",
"Darius", "Darken", "Darkle", "Darlene", "Darling", "Darrell",
"Darwin", "Dastard", "Datsun", "Dauphin", "Davies", "Davison",
"Dawson", "Daybed", "Daytime", "Dayton", "Daytona", "Dazzle",
"Deacon", "Deaden", "Deafen", "Deanna", "Dearie", "Dearth",
"Debacle", "Debase", "Debate", "Debater", "Debauch", "Debbie",
"Deborah", "Debrief", "Debris", "Debtor", "Debunk", "Debussy",
"Decade", "Decant", "Decatur", "Decease", "Deceit", "Deceive",
"Decent", "Decibel", "Decide", "Decile", "Decimal", "Decker",
"Declaim", "Declare", "Decline", "Decode", "Decorum", "Decree",
"Decrypt", "Deduce", "Deduct", "Deepen", "Deface", "Default",
"Defeat", "Defect", "Defend", "Defiant", "Deficit", "Define",
"Deflate", "Deflect", "Defocus", "Deform", "Defraud", "Defray",
"Defrock", "Defrost", "Defunct", "Defuse", "Degrade", "Degree",
"Deject", "Delaney", "Delano", "Delete", "Delicti", "Delight",
"Delilah", "Delimit", "Deliver", "Delouse", "Delphi", "Delphic",
"Deltoid", "Delude", "Deluge", "Deluxe", "Demand", "Demark",
"Demean", "Demerit", "Demigod", "Demise", "Demonic", "Demote",
"Dempsey", "Demure", "Denial", "Denizen", "Denmark", "Dennis",
"Denote", "Dental", "Denton", "Denture", "Denude", "Denver",
"Depart", "Depend", "Depict", "Deplete", "Deplore", "Deploy",
"Deport", "Depose", "Deposit", "Deprave", "Depress", "Deprive",
"Depute", "Deputy", "Derail", "Derange", "Derate", "Deride",
"Derive", "Derrick", "Dervish", "Descant", "Descend", "Descent",
"Desert", "Deserve", "Design", "Desire", "Desist", "Desmond",
"Despair", "Despise", "Despite", "Despoil", "Despond", "Despot",
"Dessert", "Destine", "Destiny", "Destroy", "Detach", "Detail",
"Detain", "Detect", "Detent", "Detente", "Detest", "Detour",
"Detract", "Detroit", "Develop", "Deviant", "Deviate", "Device",
"Devious", "Devise", "Devisee", "Devoid", "Devolve", "Devote",
"Devotee", "Devour", "Devout", "Dewdrop", "Dewitt", "Dexter",
"Dharma", "Diabase", "Diadem", "Diagram", "Dialect", "Dialup",
"Diamond", "Dianne", "Diaper", "Diatom", "Dibble", "Dickens",
"Dickey", "Dickson", "Dictate", "Diction", "Dictum", "Diddle",
"Diebold", "Diehard", "Diesel", "Dietary", "Differ", "Diffuse",
"Digest", "Digging", "Digital", "Dignify", "Dignity", "Digram",
"Digress", "Dilate", "Dilemma", "Dillon", "Diluent", "Dilute",
"Dimple", "Dinghy", "Diocese", "Diopter", "Diorama", "Diorite",
"Dioxide", "Diploid", "Diploma", "Dipole", "Direct", "Discern",
"Discoid", "Discus", "Discuss", "Disdain", "Dishes", "Dismal",
"Disney", "Dispel", "Dispute", "Disrupt", "Distaff", "Distal",
"Distant", "Distort", "Disturb", "Dither", "Ditzel", "Diurnal",
"Diverge", "Diverse", "Divert", "Divest", "Divide", "Divine",
"Divisor", "Divorce", "Divulge", "Dnieper", "Dobbin", "Dobson",
"Docile", "Docket", "Doctor", "Dodson", "Dogbane", "Dogfish",
"Dogging", "Doggone", "Dogleg", "Dogtrot", "Dogwood", "Doherty",
"Doldrum", "Doleful", "Dollar", "Dollop", "Dolores", "Dolphin",
"Doltish", "Domain", "Domingo", "Dominic", "Domino", "Donahue",
"Donald", "Donate", "Doneck", "Donkey", "Donner", "Donovan",
"Doodle", "Dooley", "Doorman", "Doormen", "Doorway", "Dopant",
"Doppler", "Dorado", "Dorcas", "Doreen", "Dormant", "Dorothy",
"Dorset", "Dosage", "Dossier", "Double", "Doublet", "Douglas",
"Dovekie", "Dowager", "Dowling", "Downey", "Downing", "Draftee",
"Drafty", "Dragnet", "Dragon", "Dragoon", "Drapery", "Drastic",
"Dreamt", "Dreamy", "Dreary", "Dredge", "Drench", "Dressy", "Drexel",
"Dribble", "Drippy", "Driven", "Drizzle", "Drizzly", "Droopy",
"Droplet", "Dropout", "Drought", "Drowse", "Drowsy", "Drudge",
"Drumlin", "Drunken", "Dryden", "Dualism", "Dubious", "Dublin",
"Duchess", "Ductile", "Dudley", "Duffel", "Dugout", "Dukedom",
"Dulcet", "Duluth", "Dumpty", "Dunbar", "Duncan", "Dunedin",
"Dungeon", "Dunham", "Dunkirk", "Dunlap", "Dunlop", "Duopoly",
"Duplex", "Dupont", "Durable", "Durance", "Durango", "Duress",
"Durham", "During", "Durkee", "Durkin", "Durrell", "Durward",
"Dustbin", "Dutiful", "Dutton", "Dwarves", "Dwight", "Dwindle",
"Dyadic", "Dyeing", "Dynamic", "Dynamo", "Dynast", "Dynasty",
"Eardrum", "Earmark", "Earnest", "Earring", "Earthen", "Earthy",
"Earwig", "Eastern", "Eastman", "Eccles", "Echelon", "Echidna",
"Echoes", "Eclipse", "Eclogue", "Ecology", "Economy", "Ecstasy",
"Ectopic", "Ecuador", "Edging", "Edible", "Edifice", "Edison",
"Edition", "Editor", "Edmonds", "Edmund", "Eduardo", "Educate",
"Edward", "Edwards", "Edwina", "Eerily", "Efface", "Effect",
"Effete", "Effort", "Egghead", "Egotism", "Egotist", "Egress",
"Ehrlich", "Eidetic", "Eighth", "Eighty", "Eileen", "Eisner",
"Either", "Ejector", "Ekstrom", "Elaine", "Elapse", "Elastic",
"Eldest", "Eleanor", "Eleazar", "Elector", "Electra", "Electro",
"Elegant", "Elegiac", "Element", "Elevate", "Eleven", "Elicit",
"Elijah", "Elinor", "Elisha", "Elision", "Elkhart", "Elliot",
"Elliott", "Ellipse", "Ellison", "Ellwood", "Elmira", "Eloise",
"Eluate", "Elusive", "Elution", "Elysee", "Elysian", "Emanate",
"Emanuel", "Embalm", "Embank", "Embargo", "Embark", "Embassy",
"Emblem", "Embody", "Emboss", "Embower", "Embrace", "Embroil",
"Embryo", "Emerald", "Emerge", "Emeriti", "Emerson", "Emilio",
"Eminent", "Emirate", "Emitted", "Emitter", "Emmett", "Emotion",
"Empathy", "Emperor", "Empire", "Empiric", "Emplace", "Employ",
"Empower", "Empress", "Emulate", "Enable", "Enamel", "Enclave",
"Encomia", "Encore", "Endemic", "Endgame", "Endorse", "Endure",
"Energy", "Enfant", "Enfield", "Engage", "Engine", "England",
"English", "Enhance", "Enigma", "Enliven", "Enmity", "Enough",
"Enquire", "Enquiry", "Enrico", "Entice", "Entire", "Entity",
"Entrant", "Entropy", "Envelop", "Envious", "Environ", "Enzyme",
"Eocene", "Eosine", "Epaulet", "Ephesus", "Ephraim", "Epicure",
"Epigram", "Episode", "Epistle", "Epitaph", "Epitaxy", "Epithet",
"Epitome", "Epochal", "Epsilon", "Epstein", "Equable", "Equate",
"Equine", "Equinox", "Equity", "Erasmus", "Erastus", "Erasure",
"Erbium", "Ergodic", "Ernest", "Erosion", "Erosive", "Erotic",
"Erotica", "Errancy", "Errand", "Errant", "Errata", "Erratic",
"Erratum", "Ersatz", "Erskine", "Erudite", "Escape", "Escapee",
"Escheat", "Eschew", "Escort", "Escrow", "Eskimo", "Esmark",
"Espouse", "Esprit", "Esquire", "Essence", "Estate", "Esteem",
"Estella", "Esther", "Estonia", "Estuary", "Eternal", "Ethane",
"Ethanol", "Ethnic", "Euclid", "Eugene", "Eugenia", "Eugenic",
"Eulogy", "Eunice", "Eurasia", "Eureka", "Europa", "Europe",
"Euterpe", "Evangel", "Evasion", "Evasive", "Evelyn", "Everett",
"Evident", "Evince", "Evocate", "Evolve", "Evzone", "Exacter",
"Examine", "Example", "Exceed", "Except", "Excerpt", "Excess",
"Excise", "Excite", "Exciton", "Exclaim", "Exclude", "Excrete",
"Excuse", "Execute", "Exegete", "Exempt", "Exeter", "Exhale",
"Exhaust", "Exhibit", "Exhort", "Exhume", "Exigent", "Exodus",
"Exogamy", "Exotic", "Exotica", "Expand", "Expanse", "Expect",
"Expend", "Expense", "Expert", "Expiate", "Expire", "Explain",
"Explode", "Exploit", "Explore", "Export", "Expose", "Exposit",
"Expound", "Express", "Expunge", "Extant", "Extend", "Extent",
"Extinct", "Extort", "Extract", "Extrema", "Extreme", "Extrude",
"Exudate", "Eyeball", "Eyebrow", "Eyeful", "Eyelash", "Eyelet",
"Eyelid", "Eyesore", "Ezekiel", "Fabian", "Fabric", "Facade",
"Facial", "Facile", "Factor", "Factory", "Factual", "Faculty",
"Fadeout", "Fafnir", "Failure", "Fairfax", "Fairway", "Falcon",
"Fallacy", "Fallen", "Falloff", "Fallout", "Fallow", "Falsify",
"Falter", "Family", "Famine", "Famish", "Famous", "Fanatic",
"Fanfare", "Fanfold", "Fangled", "Fanout", "Fantasy", "Fantod",
"Faraday", "Farber", "Farina", "Farkas", "Farley", "Farrell",
"Farther", "Fascism", "Fascist", "Fashion", "Fasten", "Fateful",
"Father", "Fathom", "Fatigue", "Fatima", "Fatten", "Fatuous",
"Faucet", "Faulty", "Faustus", "Fayette", "Fealty", "Fearful",
"Feather", "Feature", "Febrile", "Fecund", "Fedders", "Federal",
"Fedora", "Feeble", "Feeney", "Feldman", "Felice", "Felicia",
"Feline", "Fellow", "Felony", "Felsite", "Female", "Fennel",
"Fenton", "Ferber", "Fermat", "Ferment", "Fermion", "Fermium",
"Fernery", "Ferrer", "Ferret", "Ferric", "Ferris", "Ferrite",
"Ferrous", "Ferrule", "Fertile", "Fervent", "Fescue", "Festive",
"Fetish", "Fetter", "Fettle", "Feudal", "Fiance", "Fiancee",
"Fiasco", "Fibrin", "Fibrous", "Fickle", "Fiction", "Fictive",
"Fiddle", "Fidget", "Fiefdom", "Fields", "Fierce", "Fiesta",
"Fifteen", "Figaro", "Figural", "Figure", "Filbert", "Filial",
"Filled", "Filler", "Fillet", "Fillip", "Filmdom", "Filter",
"Filthy", "Finale", "Finance", "Finery", "Finesse", "Finger",
"Finial", "Finicky", "Finish", "Finite", "Finland", "Finley",
"Finnish", "Firearm", "Firebug", "Firefly", "Fireman", "Firemen",
"Fiscal", "Fischer", "Fishery", "Fissile", "Fission", "Fissure",
"Fitful", "Fitzroy", "Fixate", "Fixture", "Fizeau", "Fizzle",
"Flabby", "Flagler", "Flange", "Flannel", "Flashy", "Flatbed",
"Flatten", "Flatus", "Flaunt", "Flaxen", "Fledge", "Fleece",
"Fleeing", "Fleming", "Flemish", "Flemish", "Fleshy", "Fletch",
"Flexure", "Flight", "Flimsy", "Flinch", "Flinty", "Floppy",
"Floral", "Florid", "Florida", "Florin", "Florist", "Flounce",
"Floury", "Flowery", "Fluency", "Fluent", "Fluffy", "Flurry",
"Fluster", "Flutter", "Fluvial", "Flyway", "Fodder", "Fogarty",
"Fogging", "Foible", "Foldout", "Foliage", "Foliate", "Folksy",
"Follow", "Fondle", "Fondly", "Foolish", "Footage", "Footman",
"Footmen", "Footpad", "Foppish", "Forage", "Forbade", "Forbear",
"Forbes", "Forbid", "Forbore", "Fordham", "Foreign", "Forest",
"Forever", "Forfeit", "Forfend", "Forgave", "Forgery", "Forget",
"Forgive", "Forgot", "Forlorn", "Formal", "Formant", "Format",
"Formate", "Formic", "Formica", "Formosa", "Formula", "Forrest",
"Forsake", "Forsook", "Fortify", "Fortin", "Fortran", "Fortran",
"Fortune", "Forward", "Forwent", "Fossil", "Foster", "Fought",
"Foundry", "Fourier", "Fourth", "Foxhall", "Foxhole", "Foxtail",
"Fragile", "Frailty", "Franca", "France", "Frances", "Francis",
"Franco", "Franco", "Frankel", "Frantic", "Fraser", "Fraught",
"Frayed", "Frazier", "Frazzle", "Freckle", "Freddie", "Freddy",
"Freedom", "Freeing", "Freeman", "Freemen", "Freest", "Freeway",
"Freeze", "Freight", "French", "Frenzy", "Fresco", "Freshen",
"Fresnel", "Fresno", "Friable", "Friday", "Friend", "Frieze",
"Frigate", "Frigga", "Fright", "Frigid", "Frilly", "Fringe",
"Frisky", "Fritter", "Frizzle", "Frolic", "Frontal", "Frosty",
"Frothy", "Frowzy", "Frozen", "Frugal", "Frustum", "Fuchsia",
"Fujitsu", "Fulcrum", "Fulfill", "Fulsome", "Fulton", "Fumble",
"Functor", "Funeral", "Fungal", "Fungoid", "Fungus", "Funnel",
"Furbish", "Furious", "Furlong", "Furman", "Furnace", "Furnish",
"Furrier", "Furrow", "Further", "Furtive", "Fusible", "Fusion",
"Futile", "Future", "Gabble", "Gabbro", "Gabriel", "Gadfly",
"Gadget", "Gadwall", "Gaelic", "Gagging", "Gaggle", "Gaiety",
"Gaines", "Gainful", "Galatea", "Galatia", "Galaxy", "Galena",
"Galilee", "Gallant", "Gallery", "Galley", "Gallium", "Gallon",
"Gallop", "Gallows", "Gallup", "Gallus", "Galois", "Galway",
"Gambia", "Gambit", "Gamble", "Gambol", "Gander", "Ganges",
"Gangway", "Gannet", "Gannett", "Gantlet", "Gantry", "Garage",
"Garbage", "Garble", "Garcia", "Garden", "Gardner", "Gargle",
"Garish", "Garland", "Garlic", "Garner", "Garnet", "Garrett",
"Garter", "Garvey", "Gascony", "Gaseous", "Gasify", "Gasket",
"Gasohol", "Gaspee", "Gaston", "Gateway", "Gather", "Gauche",
"Gauguin", "Gaulle", "Gavotte", "Gaylord", "Gazelle", "Gazette",
"Geiger", "Geisha", "Gelable", "Gelatin", "Gemini", "Gemlike",
"Gender", "Genera", "General", "Generic", "Genesco", "Genesis",
"Genetic", "Geneva", "Genial", "Genital", "Genius", "Genteel",
"Gentian", "Gentile", "Gentle", "Gentry", "Genuine", "Geodesy",
"Geoduck", "Geology", "George", "Georgia", "Gerald", "Gerard",
"Gerber", "Gerbil", "Gerhard", "German", "Germane", "Germany",
"Gerund", "Gestalt", "Gestapo", "Gesture", "Getaway", "Geyser",
"Ghastly", "Gherkin", "Ghetto", "Ghostly", "Giacomo", "Gibbet",
"Gibbon", "Gibbons", "Gibbous", "Giblet", "Gibson", "Giddap",
"Gideon", "Gifford", "Gigabit", "Gigging", "Giggle", "Gilbert",
"Gilead", "Gilmore", "Gimbal", "Gimbel", "Gimmick", "Ginger",
"Gingham", "Gingko", "Ginkgo", "Ginmill", "Ginseng", "Giraffe",
"Girdle", "Girlie", "Girlish", "Giveth", "Glacial", "Glacier",
"Glacis", "Gladden", "Gladdy", "Gladys", "Glamor", "Glamour",
"Glance", "Glasgow", "Glassy", "Gleason", "Gleeful", "Glenda",
"Glidden", "Glimmer", "Glimpse", "Glisten", "Glitch", "Glitter",
"Global", "Globule", "Gloomy", "Gloria", "Glorify", "Glossed",
"Glossy", "Glottal", "Glottis", "Glucose", "Gluing", "Glutton",
"Glycine", "Glycol", "Gneiss", "Gnomon", "Gnostic", "Gobble",
"Goblet", "Goddard", "Goddess", "Godfrey", "Godhead", "Godkin",
"Godlike", "Godsend", "Godson", "Godwin", "Godwit", "Goethe",
"Goggle", "Golden", "Goldman", "Goleta", "Goliath", "Gondola",
"Goober", "Goodbye", "Goodman", "Goodwin", "Gopher", "Gordian",
"Gordon", "Gorgon", "Gorham", "Gorilla", "Gorton", "Goshawk",
"Gosling", "Gospel", "Gossip", "Gotham", "Gothic", "Gotten",
"Goucher", "Gourmet", "Govern", "Grackle", "Gradate", "Gradual",
"Graham", "Grainy", "Grammar", "Granary", "Grandma", "Grandpa",
"Granite", "Granny", "Granola", "Grantee", "Grantor", "Granule",
"Graphic", "Grapple", "Grassy", "Grater", "Gratify", "Gratis",
"Gravel", "Graven", "Graves", "Gravid", "Grayish", "Grayson",
"Grease", "Greasy", "Greater", "Grecian", "Greece", "Greedy",
"Greene", "Gregory", "Gremlin", "Grenade", "Grendel", "Gresham",
"Greylag", "Griddle", "Grieve", "Griffin", "Grille", "Grilled",
"Grimace", "Grimes", "Grippe", "Grisly", "Gritty", "Grizzle",
"Grizzly", "Grocer", "Grocery", "Groggy", "Grommet", "Groove",
"Grosset", "Groton", "Ground", "Grovel", "Grover", "Grownup",
"Growth", "Grubby", "Grudge", "Grumble", "Grumman", "Gryphon",
"Guanine", "Guardia", "Guelph", "Guerdon", "Guffaw", "Guiana",
"Guiding", "Guignol", "Guilty", "Guinea", "Guitar", "Gullah",
"Gullet", "Gumdrop", "Gumshoe", "Gunfire", "Gunman", "Gunmen",
"Gunnery", "Gunplay", "Gunshot", "Gunther", "Gurgle", "Gurkha",
"Gusset", "Gustav", "Gustave", "Guthrie", "Guyana", "Guzzle",
"Gymnast", "Gypsite", "Gypsum", "Gyrate", "Habeas", "Habitat",
"Hackett", "Hackle", "Hackney", "Hacksaw", "Haddad", "Haddock",
"Hadley", "Hadrian", "Hadron", "Hafnium", "Haggard", "Haggle",
"Haines", "Haircut", "Hairdo", "Hairpin", "Haitian", "Halcyon",
"Halfway", "Halibut", "Halide", "Halifax", "Halite", "Halley",
"Hallow", "Hallway", "Halogen", "Halpern", "Halsey", "Halvah",
"Hamburg", "Hamlet", "Hamlin", "Hammock", "Hammond", "Hamper",
"Hampton", "Hamster", "Hancock", "Handbag", "Handel", "Handful",
"Handgun", "Handle", "Handout", "Handset", "Hanford", "Hangar",
"Hangman", "Hangmen", "Hangout", "Hankel", "Hanley", "Hanlon",
"Hannah", "Hanover", "Hansel", "Hansen", "Hansom", "Hanson",
"Haploid", "Happen", "Harass", "Harbin", "Harden", "Hardhat",
"Hardin", "Harding", "Hardtop", "Harelip", "Harlan", "Harlem",
"Harley", "Harmful", "Harmon", "Harmony", "Harness", "Harold",
"Harpoon", "Harriet", "Harris", "Harrow", "Harshen", "Hartley",
"Hartman", "Harvard", "Harvest", "Harvey", "Hashish", "Hassle",
"Hasten", "Hatchet", "Hateful", "Hatred", "Hattie", "Haugen",
"Haughty", "Haulage", "Haunch", "Havana", "Hawaii", "Hawkins",
"Hawley", "Hayden", "Haynes", "Hayward", "Hayward", "Hazard",
"Headset", "Headway", "Healey", "Health", "Healthy", "Hearken",
"Hearsay", "Hearse", "Hearst", "Hearten", "Hearth", "Hearty",
"Heater", "Heathen", "Heaven", "Hebraic", "Hebrew", "Hecate",
"Heckle", "Heckman", "Hectic", "Hector", "Hecuba", "Height",
"Heiress", "Helena", "Helene", "Helical", "Helium", "Hellish",
"Helmet", "Helmut", "Helpful", "Hemlock", "Henbane", "Henley",
"Henpeck", "Hepburn", "Heptane", "Herald", "Herbert", "Hereby",
"Herein", "Hereof", "Heresy", "Heretic", "Hereto", "Herman",
"Hermann", "Hermes", "Hermite", "Hermosa", "Heroes", "Heroic",
"Heroin", "Heroine", "Heroism", "Herpes", "Herself", "Hershel",
"Hershey", "Hertzog", "Hessian", "Hester", "Hetman", "Hettie",
"Heusen", "Heuser", "Hewett", "Hewitt", "Hewlett", "Hexagon",
"Hexane", "Heyday", "Hiatus", "Hibachi", "Hibbard", "Hickey",
"Hickman", "Hickory", "Hidalgo", "Hidden", "Hideous", "Hideout",
"Higgins", "Highboy", "Highest", "Highway", "Hijack", "Hijinks",
"Hilbert", "Hillel", "Hillman", "Hillmen", "Hillock", "Hilltop",
"Hilton", "Himself", "Hinman", "Hipster", "Hiroshi", "Hirsch",
"Hirsute", "History", "Hitachi", "Hither", "Hitler", "Hoagie",
"Hoarse", "Hobart", "Hobbes", "Hobble", "Hoboken", "Hockey",
"Hodges", "Hodgkin", "Hoffman", "Hogging", "Holcomb", "Holden",
"Holdout", "Holdup", "Holiday", "Holland", "Holler", "Hollow",
"Holman", "Holmdel", "Holmes", "Holmium", "Holster", "Holyoke",
"Homage", "Homeown", "Homeric", "Homily", "Homonym", "Honest",
"Honesty", "Honoree", "Honshu", "Hoodlum", "Hookup", "Hoopla",
"Hoosier", "Hoover", "Hooves", "Hopeful", "Hopkins", "Hopple",
"Horace", "Horatio", "Horizon", "Hormone", "Hornet", "Horrid",
"Horrify", "Horror", "Horton", "Hosiery", "Hospice", "Hostage",
"Hostess", "Hostile", "Hostler", "Hotbed", "Hotbox", "Hothead",
"Hotrod", "Hotshot", "Houdini", "Houston", "Howard", "Howell",
"However", "Hoyden", "Hubbard", "Hubbell", "Hubbub", "Hubert",
"Hubris", "Huddle", "Hudson", "Huffman", "Hugging", "Huggins",
"Hughes", "Humane", "Humble", "Humerus", "Hummel", "Hummock",
"Humpty", "Hundred", "Hungary", "Hungry", "Hunter", "Huntley",
"Hurdle", "Hurley", "Hurrah", "Hurray", "Hurtle", "Hurwitz",
"Husband", "Hustle", "Huston", "Huxley", "Huzzah", "Hyades",
"Hyaline", "Hyannis", "Hybrid", "Hydrant", "Hydrate", "Hydride",
"Hydrous", "Hydroxy", "Hygiene", "Hymnal", "Hyphen", "Iambic",
"Iberia", "Icarus", "Iceberg", "Icebox", "Iceland", "Iceland",
"Icicle", "Iconic", "Ideate", "Idiocy", "Idiotic", "Idyllic",
"Igneous", "Ignite", "Ignoble", "Ignore", "Illegal", "Illicit",
"Illogic", "Illume", "Imagen", "Imagery", "Imagine", "Imbibe",
"Imbrium", "Imbrue", "Imitate", "Immense", "Immerse", "Immoral",
"Immune", "Impact", "Impair", "Impale", "Impart", "Impasse",
"Impeach", "Impede", "Impend", "Imperil", "Impetus", "Impiety",
"Impinge", "Impious", "Impish", "Implant", "Implode", "Implore",
"Import", "Impose", "Impost", "Impound", "Impress", "Imprint",
"Improve", "Impugn", "Impulse", "Impure", "Impute", "Inboard",
"Inborn", "Inbred", "Inbreed", "Incant", "Incense", "Incest",
"Incise", "Incite", "Incline", "Inclose", "Include", "Income",
"Incubi", "Incubus", "Indeed", "Indent", "Indian", "Indiana",
"Indices", "Indict", "Indies", "Indigo", "Indira", "Indium",
"Indoor", "Indorse", "Induce", "Induct", "Indulge", "Indwell",
"Inertia", "Inexact", "Infamy", "Infancy", "Infant", "Infarct",
"Infect", "Inferno", "Infest", "Infidel", "Infield", "Infight",
"Infima", "Infimum", "Infirm", "Inflame", "Inflate", "Inflect",
"Inflict", "Inflow", "Influx", "Inform", "Infract", "Infuse",
"Ingest", "Ingram", "Ingrate", "Ingrown", "Inhabit", "Inhale",
"Inhere", "Inherit", "Inhibit", "Inhuman", "Initial", "Inject",
"Injunct", "Injure", "Injury", "Inkling", "Inlaid", "Inland",
"Inmate", "Innards", "Innate", "Inquest", "Inquire", "Inquiry",
"Inroad", "Insane", "Insect", "Insert", "Inshore", "Inside",
"Insight", "Insipid", "Insist", "Insofar", "Inspect", "Inspire",
"Install", "Instant", "Instead", "Instep", "Instill", "Insular",
"Insulin", "Insult", "Insure", "Intact", "Intake", "Integer",
"Intend", "Intense", "Intent", "Interim", "Intern", "Intimal",
"Intone", "Introit", "Intrude", "Intuit", "Invade", "Invalid",
"Inveigh", "Invent", "Inverse", "Invert", "Invest", "Invite",
"Invitee", "Invoice", "Invoke", "Involve", "Inward", "Iodate",
"Iodide", "Iodine", "Ipecac", "Iranian", "Ireland", "Iridium",
"Irksome", "Ironic", "Irvine", "Irving", "Isabel", "Isadore",
"Isaiah", "Isfahan", "Islamic", "Island", "Isolate", "Isolde",
"Isomer", "Isotope", "Israel", "Israeli", "Issuant", "Istvan",
"Italian", "Italic", "Iterate", "Ithaca", "Itself", "Ivanhoe",
"Iverson", "Jackass", "Jackdaw", "Jacket", "Jackie", "Jackman",
"Jackpot", "Jackson", "Jacobi", "Jacobs", "Jacobus", "Jacques",
"Jaeger", "Jagging", "Jaguar", "Jakarta", "Jalopy", "Jamaica",
"Janeiro", "Jangle", "Janice", "Janitor", "January", "Jargon",
"Jarvin", "Jasper", "Jaunty", "Javelin", "Jawbone", "Jealous",
"Jeannie", "Jeffrey", "Jehovah", "Jejune", "Jejunum", "Jenkins",
"Jennie", "Jensen", "Jeopard", "Jeremy", "Jericho", "Jerome",
"Jersey", "Jessica", "Jessie", "Jesuit", "Jewell", "Jewelry",
"Jewett", "Jewish", "Jigging", "Jiggle", "Jigsaw", "Jimenez",
"Jimmie", "Jingle", "Jitter", "Jittery", "Joanna", "Joanne",
"Joaquin", "Jockey", "Jocose", "Jocular", "Jocund", "Jogging",
"Joggle", "Johann", "Johnny", "Johnsen", "Johnson", "Joliet",
"Jonquil", "Jordan", "Joseph", "Joshua", "Josiah", "Jostle",
"Jounce", "Journal", "Journey", "Jovial", "Jovian", "Joyful",
"Joyous", "Joyride", "Juanita", "Jubilee", "Judaism", "Judith",
"Judson", "Jugate", "Jugging", "Juggle", "Jujube", "Juliet",
"Julius", "Jumble", "Junctor", "Juneau", "Jungle", "Junior",
"Juniper", "Jupiter", "Juridic", "Justice", "Justify", "Justine",
"Jutish", "Kabuki", "Kaddish", "Kaiser", "Kalmia", "Kalmuk",
"Kampala", "Kansas", "Kaolin", "Kaplan", "Karachi", "Karate",
"Kaufman", "Keaton", "Keddah", "Keelson", "Keenan", "Keller",
"Kelley", "Kellogg", "Kelsey", "Kelvin", "Kendall", "Kennan",
"Kennedy", "Kennel", "Kenneth", "Kenney", "Kenton", "Kenyon",
"Kepler", "Kermit", "Kernel", "Kerygma", "Kessler", "Kestrel",
"Ketchup", "Ketone", "Ketosis", "Kettle", "Keyhole", "Keynes",
"Keynote", "Keyword", "Kibitz", "Kickoff", "Kiddie", "Kidnap",
"Kidney", "Kieffer", "Kiewit", "Kigali", "Kikuyu", "Kilgore",
"Killjoy", "Kilohm", "Kimball", "Kimono", "Kindle", "Kindred",
"Kinesic", "Kinetic", "Kingdom", "Kinglet", "Kingpin", "Kinney",
"Kipling", "Kissing", "Kitchen", "Kitten", "Kittle", "Kiwanis",
"Klaxon", "Kleenex", "Knauer", "Kneecap", "Knight", "Knives",
"Knobby", "Knotty", "Knoweth", "Knowhow", "Knowles", "Knuckle",
"Knudsen", "Knudson", "Knutsen", "Knutson", "Kochab", "Kodiak",
"Koenig", "Kolkhoz", "Konrad", "Koppers", "Kosher", "Kovacs",
"Kowloon", "Krakow", "Kramer", "Krause", "Kremlin", "Kresge",
"Krieger", "Krishna", "Kristin", "Krueger", "Kruger", "Krypton",
"Kumquat", "Kuwait", "Labial", "Labile", "Labour", "Lacerta",
"Lackey", "Laconic", "Lacquer", "Lactate", "Lactose", "Lacuna",
"Lacunae", "Lagging", "Lagoon", "Lahore", "Laidlaw", "Laissez",
"Lamarck", "Lambda", "Lambert", "Lament", "Laminar", "Lampoon",
"Lamprey", "Landau", "Landis", "Langley", "Languid", "Lansing",
"Lantern", "Laocoon", "Laotian", "Laplace", "Lappet", "Laramie",
"Larceny", "Laredo", "Lariat", "Larkin", "Larsen", "Larson",
"Larvae", "Larval", "Larynx", "Lascar", "Laszlo", "Latent", "Latera",
"Lateral", "Lateran", "Lathrop", "Latrobe", "Latter", "Lattice",
"Latvia", "Launch", "Launder", "Laundry", "Laurel", "Lauren",
"Laurent", "Laurie", "Lavabo", "Lavish", "Lawful", "Lawgive",
"Lawmake", "Lawman", "Lawmen", "Lawson", "Lawsuit", "Lawyer",
"Layette", "Layman", "Laymen", "Layoff", "Layout", "Layton",
"Lazarus", "Leaden", "Leadeth", "Leaflet", "League", "Leakage",
"Leander", "Leather", "Leaven", "Lebanon", "Lecher", "Lechery",
"Lectern", "Lecture", "Leeward", "Leeway", "Legacy", "Legate",
"Legatee", "Legato", "Legend", "Legging", "Leghorn", "Legible",
"Legion", "Legume", "Lehigh", "Lehman", "Leisure", "Leland",
"Lemming", "Lemuel", "Length", "Lengthy", "Lenient", "Lennox",
"Lenore", "Lenten", "Lentil", "Leonard", "Leonid", "Leonine",
"Leopard", "Leopold", "Leprosy", "Lesbian", "Lesbian", "Lesion",
"Leslie", "Lesotho", "Lessee", "Lessen", "Lesson", "Lessor",
"Lester", "Lethal", "Letitia", "Lettuce", "Leucine", "Levine",
"Levitt", "Levity", "Lexical", "Lexicon", "Leyden", "Liable",
"Liaison", "Liberal", "Liberia", "Liberty", "Libido", "Library",
"Librate", "Lichen", "Ligand", "Ligget", "Liggett", "Lighten",
"Lignite", "Lignum", "Lilian", "Lillian", "Limbic", "Limpet",
"Limpid", "Limpkin", "Lincoln", "Linden", "Lindsay", "Lindsey",
"Lineage", "Lineal", "Linear", "Lineman", "Linemen", "Lineup",
"Linger", "Lingua", "Lingual", "Linkage", "Linseed", "Lionel",
"Lioness", "Lipread", "Lipton", "Liquefy", "Liqueur", "Liquid",
"Liquor", "Lisbon", "Listen", "Litany", "Literal", "Lithic",
"Lithium", "Litmus", "Little", "Litton", "Liturgy", "Livery",
"Liveth", "Lizard", "Lizzie", "Loathe", "Loaves", "Lobster",
"Lobular", "Lobule", "Locale", "Locate", "Lockian", "Locknut",
"Lockout", "Lockup", "Locust", "Locutor", "Logging", "Logjam",
"Loiter", "Lombard", "London", "Longish", "Longleg", "Longue",
"Lookout", "Lookup", "Loomis", "Loosen", "Lopseed", "Loquat",
"Lorelei", "Lorenz", "Loretta", "Lorinda", "Losable", "Lotion",
"Lottery", "Lottie", "Louisa", "Louise", "Lounge", "Lourdes",
"Louver", "Louvre", "Lowboy", "Lowdown", "Lowell", "Lowland",
"Loyalty", "Lozenge", "Lubbock", "Lubell", "Lucerne", "Lucian",
"Lucifer", "Lucille", "Lucius", "Ludlow", "Ludwig", "Luggage",
"Lugging", "Lukemia", "Lullaby", "Lumbar", "Lumber", "Lummox",
"Lumpish", "Lumpur", "Lunacy", "Lunary", "Lunate", "Lunatic",
"Lupine", "Lusaka", "Lustful", "Luther", "Luxury", "Lysenko",
"Lysine", "Macabre", "Macaque", "Macbeth", "Macedon", "Machine",
"Mackey", "Macrame", "Madame", "Madcap", "Madden", "Maddox",
"Madeira", "Madison", "Madman", "Madmen", "Madonna", "Madras",
"Madrid", "Madsen", "Maestro", "Magenta", "Maggie", "Maggot",
"Maggoty", "Magnate", "Magnet", "Magneto", "Magnify", "Magnum",
"Magpie", "Mahoney", "Maiden", "Mailbox", "Mailman", "Mailmen",
"Maitre", "Majesty", "Makeup", "Malabar", "Malady", "Malaise",
"Malaria", "Malawi", "Malcolm", "Malden", "Maldive", "Malice",
"Malign", "Mallard", "Mallet", "Mallory", "Mallow", "Malone",
"Maloney", "Malraux", "Maltese", "Malton", "Maltose", "Mammal",
"Mammoth", "Manage", "Managua", "Manama", "Manatee", "Mandate",
"Mandrel", "Manfred", "Mangel", "Mangle", "Manhole", "Manhood",
"Maniac", "Manikin", "Manila", "Mankind", "Manley", "Mansion",
"Mantel", "Mantic", "Mantis", "Mantle", "Mantrap", "Manual",
"Manuel", "Manumit", "Manure", "Maraud", "Marble", "Marceau",
"Marcel", "Marcia", "Marcus", "Margery", "Margin", "Marilyn",
"Marimba", "Marina", "Marine", "Marino", "Marion", "Marital",
"Marjory", "Market", "Markham", "Markov", "Marlene", "Marlin",
"Marlowe", "Marmot", "Maroon", "Marque", "Marquee", "Marquis",
"Married", "Marrow", "Marsha", "Marshal", "Marten", "Martha",
"Martial", "Martian", "Martin", "Martini", "Martyr", "Marvel",
"Marvin", "Mascara", "Maseru", "Masonic", "Masonry", "Masque",
"Massage", "Masseur", "Massey", "Massif", "Massive", "Mastery",
"Mastic", "Mastiff", "Mathews", "Mathias", "Mathieu", "Matilda",
"Matinal", "Matinee", "Matins", "Matisse", "Matrix", "Matroid",
"Matron", "Matson", "Matthew", "Mattock", "Mattson", "Mature",
"Maudlin", "Maureen", "Maurice", "Maurine", "Mawkish", "Maxima",
"Maximal", "Maximum", "Maxine", "Maxwell", "Mayfair", "Mayhem",
"Maynard", "Mayoral", "Mazurka", "Mbabane", "Mcadams", "Mcbride",
"Mccabe", "Mccall", "Mccann", "Mccarty", "Mcclain", "Mcclure",
"Mcelroy", "Mcgill", "Mcgowan", "Mcgrath", "Mcgraw", "Mcguire",
"Mchugh", "Mckenna", "Mckeon", "Mclean", "Mcleod", "Mcmahon",
"Mcnally", "Mcneil", "Mcnulty", "Meadow", "Meager", "Meander",
"Measle", "Measure", "Meddle", "Medford", "Medial", "Median",
"Mediate", "Medici", "Medico", "Medium", "Medlar", "Medley",
"Medusa", "Megabit", "Megaton", "Megohm", "Meiosis", "Mekong",
"Melange", "Melanie", "Melanin", "Melcher", "Melinda", "Melissa",
"Mellon", "Mellow", "Melodic", "Melody", "Melvin", "Member",
"Memento", "Memoir", "Memory", "Memphis", "Menace", "Mendel",
"Menfolk", "Menial", "Mental", "Mention", "Mentor", "Menzies",
"Mercer", "Mercury", "Merlin", "Mermaid", "Merriam", "Merrill",
"Merritt", "Mervin", "Mescal", "Message", "Messiah", "Messiah",
"Messrs", "Metcalf", "Meteor", "Methane", "Method", "Methuen",
"Methyl", "Metier", "Metric", "Mettle", "Metzler", "Mexican",
"Mexico", "Meyers", "Miasma", "Miasmal", "Michael", "Michel",
"Michele", "Mickey", "Micron", "Midband", "Midday", "Middle",
"Midget", "Midland", "Midmorn", "Midspan", "Midterm", "Midway",
"Midweek", "Midwest", "Midwife", "Mighty", "Mignon", "Migrant",
"Migrate", "Miguel", "Mildew", "Mildred", "Mileage", "Milieu",
"Militia", "Millard", "Miller", "Millet", "Millie", "Million",
"Milord", "Milton", "Mimesis", "Mimetic", "Minaret", "Mindful",
"Mineral", "Minerva", "Mingle", "Minima", "Minimal", "Minimax",
"Minimum", "Minion", "Minnie", "Minnow", "Minoan", "Minsky",
"Minuend", "Minuet", "Minute", "Miocene", "Miracle", "Mirage",
"Miranda", "Mirfak", "Miriam", "Mirror", "Misery", "Missile",
"Mission", "Missive", "Mitosis", "Mitral", "Mitten", "Mixture",
"Mobcap", "Mobile", "Mobster", "Mockery", "Mockup", "Modern",
"Modest", "Modesto", "Modesty", "Modicum", "Modify", "Modish",
"Modular", "Module", "Moduli", "Modulo", "Modulus", "Mohawk",
"Moiety", "Moines", "Moisten", "Molest", "Moliere", "Moline",
"Mollie", "Mollify", "Mollusk", "Moloch", "Molten", "Moment",
"Momenta", "Monaco", "Monadic", "Monarch", "Monash", "Monday",
"Monica", "Monies", "Monitor", "Monkey", "Monkish", "Monoid",
"Monomer", "Monroe", "Monsoon", "Monster", "Montage", "Montana",
"Mooney", "Moonlit", "Moorish", "Moraine", "Morale", "Morass",
"Moravia", "Morbid", "Moresby", "Morgan", "Morgen", "Morgue",
"Morley", "Mormon", "Morocco", "Morose", "Morrill", "Morris",
"Morrow", "Morsel", "Mortal", "Mortar", "Mortem", "Mortify",
"Mortise", "Morton", "Mosaic", "Moscow", "Moslem", "Mosque",
"Mother", "Motion", "Motive", "Motley", "Mottle", "Moulton",
"Mouton", "Mozart", "Mucosa", "Muddle", "Mueller", "Muezzin",
"Muffin", "Muffle", "Mugging", "Mukden", "Mulatto", "Mulish",
"Mullah", "Mullein", "Mullen", "Mullion", "Mumble", "Mumford",
"Muncie", "Mundane", "Munich", "Munson", "Murder", "Muriel",
"Murmur", "Murphy", "Murray", "Muscat", "Muscle", "Muscovy",
"Museum", "Musket", "Muskox", "Muskrat", "Muslim", "Muslim",
"Muslin", "Mussel", "Mustang", "Mustard", "Mutagen", "Mutant",
"Mutate", "Mutatis", "Mutiny", "Mutter", "Mutton", "Mutual",
"Mutuel", "Muzzle", "Mycenae", "Myeline", "Myeloid", "Mynheer",
"Myopia", "Myopic", "Myosin", "Myriad", "Myrtle", "Myself",
"Mystery", "Mystic", "Mystify", "Mythic", "Nabisco", "Nadine",
"Nagging", "Nagoya", "Nairobi", "Naivete", "Nanette", "Nanking",
"Napkin", "Naples", "Narrate", "Narrow", "Nascent", "Nashua",
"Nassau", "Natalie", "Natchez", "Nathan", "Nation", "Native",
"Natural", "Nature", "Naughty", "Nausea", "Nauseum", "Navajo",
"Nazism", "Nearby", "Nearest", "Neater", "Nebula", "Nebulae",
"Nebular", "Necktie", "Nectar", "Nectary", "Needful", "Needham",
"Needham", "Needle", "Negate", "Neglect", "Negroes", "Negroid",
"Neither", "Nellie", "Nelsen", "Nelson", "Nemesis", "Neonate",
"Nephew", "Neptune", "Nereid", "Nervous", "Nestle", "Nestor",
"Nether", "Nettle", "Network", "Neumann", "Neural", "Neuron",
"Neuter", "Neutral", "Neutron", "Nevada", "Nevins", "Newark",
"Newbold", "Newborn", "Newell", "Newline", "Newman", "Newport",
"Newsboy", "Newsman", "Newsmen", "Newton", "Nguyen", "Niacin",
"Niagara", "Niamey", "Nibble", "Nicety", "Nichols", "Nickel",
"Nicosia", "Nielsen", "Nielson", "Nigeria", "Nigger", "Niggle",
"Nikolai", "Nimble", "Nimbus", "Ninety", "Nineveh", "Niobium",
"Nipple", "Nippon", "Nirvana", "Nitpick", "Nitrate", "Nitric",
"Nitride", "Nitrite", "Nitrous", "Nobody", "Nodular", "Nodule",
"Nomadic", "Nominal", "Nominee", "Noodle", "Noreen", "Norfolk",
"Normal", "Norman", "Norris", "Norton", "Norwalk", "Norway",
"Norwich", "Nosebag", "Nostril", "Notary", "Notate", "Nothing",
"Notice", "Notify", "Notion", "Nourish", "Nouveau", "Novelty",
"Novice", "Nowaday", "Nowhere", "Nowise", "Noxious", "Nozzle",
"Nuance", "Nubile", "Nuclear", "Nuclei", "Nucleic", "Nucleus",
"Nuclide", "Nugget", "Nullify", "Numeral", "Numeric", "Nuptial",
"Nursery", "Nurture", "Nutate", "Nutmeg", "Nutria", "Nuzzle",
"Nyquist", "Oakland", "Oakley", "Oakwood", "Oatmeal", "Obelisk",
"Oberlin", "Object", "Oblate", "Oblige", "Oblique", "Oblong",
"Oboist", "Obscene", "Obscure", "Obsequy", "Observe", "Obsess",
"Obtain", "Obtrude", "Obverse", "Obviate", "Obvious", "Ocarina",
"Occlude", "Occult", "Occupy", "Oceania", "Oceanic", "Ocelot",
"Octagon", "Octane", "Octant", "Octave", "Octavia", "Octile",
"October", "Octopus", "Ocular", "Odessa", "Odious", "Odorous",
"Odyssey", "Oedipal", "Oedipus", "Oersted", "Offbeat", "Offend",
"Offhand", "Office", "Officio", "Offload", "Offset", "Ogress",
"Oilman", "Oilmen", "Oilseed", "Okinawa", "Oldster", "Olefin",
"Oliver", "Olivia", "Olivine", "Olympia", "Olympic", "Omelet",
"Omicron", "Ominous", "Omitted", "Omnibus", "Oneida", "Onerous",
"Oneself", "Onetime", "Ongoing", "Onlook", "Onrush", "Ontario",
"Onward", "Oocyte", "Oodles", "Opacity", "Opaque", "Operand",
"Operant", "Operate", "Operon", "Opiate", "Opinion", "Opossum",
"Oppose", "Oppress", "Optima", "Optimal", "Optimum", "Option",
"Opulent", "Oracle", "Orange", "Oratory", "Orbital", "Orchard",
"Orchid", "Orchis", "Ordain", "Ordeal", "Orderly", "Ordinal",
"Oregano", "Oregon", "Orestes", "Organdy", "Organic", "Orgasm",
"Orient", "Orifice", "Origin", "Orinoco", "Oriole", "Orkney",
"Orlando", "Orleans", "Ornate", "Ornery", "Orphan", "Orpheus",
"Orphic", "Ortega", "Orthant", "Orville", "Orwell", "Osborn",
"Osborne", "Osgood", "Oshkosh", "Osiris", "Osmium", "Osmosis",
"Osmotic", "Osprey", "Osseous", "Ossify", "Ostrich", "Oswald",
"Othello", "Otiose", "Ottawa", "Ottoman", "Oviform", "Oxalate",
"Oxalic", "Oxcart", "Oxford", "Oxidant", "Oxidate", "Oxnard",
"Oxonian", "Oxygen", "Oyster", "Pacific", "Pacify", "Package",
"Packard", "Packet", "Paddle", "Paddock", "Padlock", "Pageant",
"Pagoda", "Painful", "Palace", "Palate", "Palazzi", "Palazzo",
"Palermo", "Palette", "Palfrey", "Pallet", "Pallid", "Palmate",
"Palmyra", "Palomar", "Pamela", "Pamper", "Panacea", "Panama",
"Pancake", "Pancho", "Pander", "Pandora", "Panicky", "Panicle",
"Panoply", "Panther", "Pantry", "Papacy", "Papery", "Papoose",
"Pappas", "Paprika", "Papyri", "Papyrus", "Parade", "Paradox",
"Paragon", "Paramus", "Parapet", "Parasol", "Parboil", "Parcel",
"Pardon", "Parent", "Pareto", "Pariah", "Parish", "Parkish",
"Parkway", "Parlay", "Parley", "Parody", "Parole", "Parolee",
"Parquet", "Parrish", "Parrot", "Parsley", "Parsnip", "Parson",
"Parsons", "Partake", "Partial", "Partner", "Partook", "Parvenu",
"Pascal", "Paschal", "Passage", "Passaic", "Passer", "Passion",
"Passive", "Pastel", "Pasteup", "Pasteur", "Pastime", "Pastor",
"Pastry", "Pasture", "Patchy", "Patent", "Pathos", "Pathway",
"Patient", "Patina", "Patrice", "Patrick", "Patriot", "Patrol",
"Patron", "Pattern", "Patton", "Paucity", "Pauline", "Paulsen",
"Paulson", "Paulus", "Paunch", "Paunchy", "Pauper", "Pavanne",
"Pavlov", "Payday", "Payoff", "Payroll", "Peabody", "Peacock",
"Peafowl", "Peanut", "Pearce", "Pearson", "Peasant", "Pebble",
"Peccary", "Pedant", "Peddle", "Pegasus", "Pegging", "Peking",
"Pelham", "Pelican", "Pellet", "Peltry", "Pelvic", "Pelvis",
"Penalty", "Penance", "Penates", "Pencil", "Pendant", "Penguin",
"Penman", "Penmen", "Pennant", "Penrose", "Pension", "Pensive",
"Pentane", "Penury", "People", "Peoria", "Peppery", "Pepsico",
"Peptide", "Percent", "Percept", "Perfect", "Perfidy", "Perform",
"Perfume", "Perfuse", "Perhaps", "Perilla", "Period", "Perish",
"Perjure", "Perjury", "Perkins", "Permian", "Permit", "Permute",
"Perplex", "Perseus", "Persia", "Persian", "Persist", "Person",
"Persona", "Pertain", "Perturb", "Perusal", "Peruse", "Pervade",
"Pervert", "Pestle", "Petite", "Petrel", "Petrify", "Petrol",
"Petunia", "Peugeot", "Pewter", "Pfennig", "Pfizer", "Phalanx",
"Phantom", "Pharaoh", "Phelps", "Phenol", "Phenyl", "Philip",
"Phillip", "Phipps", "Phloem", "Phobic", "Phoebe", "Phoenix",
"Phoneme", "Phonic", "Phonon", "Photon", "Phrase", "Phyllis",
"Physic", "Physik", "Pianist", "Piazza", "Picasso", "Piccolo",
"Pickaxe", "Picket", "Pickett", "Pickle", "Pickman", "Pickoff",
"Pickup", "Picnic", "Picture", "Piddle", "Pidgin", "Pierce",
"Pierre", "Pierson", "Pietism", "Pigeon", "Pigging", "Piggish",
"Pigment", "Pigpen", "Pigroot", "Pigskin", "Pigtail", "Pilate",
"Pilfer", "Pilgrim", "Pillage", "Pillar", "Pillory", "Pillow",
"Pimple", "Pinball", "Pinhead", "Pinhole", "Pinion", "Pinkie",
"Pinkish", "Pinnate", "Pinsky", "Pintail", "Pinxter", "Pioneer",
"Pipette", "Piquant", "Piracy", "Piraeus", "Pirate", "Pirogue",
"Pisces", "Pistol", "Pistole", "Piston", "Piteous", "Pitfall",
"Pitiful", "Pitman", "Pitney", "Pivotal", "Placate", "Placebo",
"Placid", "Plague", "Plagued", "Plaguey", "Planar", "Planck",
"Planet", "Plaque", "Plasma", "Plasmon", "Plaster", "Plastic",
"Plateau", "Platen", "Platoon", "Platte", "Playboy", "Playful",
"Playoff", "Please", "Plebian", "Pledge", "Plenary", "Plenty",
"Plenum", "Pleura", "Pleural", "Pliable", "Pliancy", "Pliant",
"Pliers", "Plight", "Plover", "Plowman", "Plucky", "Plumage",
"Plummet", "Plunder", "Plunge", "Plural", "Plushy", "Pluton",
"Plywood", "Pocket", "Pocono", "Podium", "Poetic", "Poetry",
"Pogrom", "Poison", "Poisson", "Poland", "Polaris", "Polaron",
"Polecat", "Polemic", "Police", "Policy", "Polish", "Polite",
"Politic", "Polity", "Pollard", "Pollen", "Pollock", "Polloi",
"Pollute", "Pollux", "Polygon", "Polymer", "Pomade", "Pomona",
"Pompano", "Pompeii", "Pompey", "Pompon", "Pompous", "Poncho",
"Ponder", "Pontiac", "Pontiff", "Poodle", "Popcorn", "Popish",
"Poplar", "Poplin", "Popular", "Porcine", "Porous", "Portage",
"Portal", "Portend", "Portent", "Portia", "Portico", "Portray",
"Posable", "Poseur", "Posner", "Possess", "Possum", "Postage",
"Postal", "Postfix", "Postman", "Postmen", "Posture", "Postwar",
"Potable", "Potash", "Potato", "Potboil", "Potent", "Pothole",
"Potion", "Potomac", "Pottery", "Poultry", "Pounce", "Poverty",
"Powder", "Powdery", "Powell", "Powers", "Praecox", "Prague",
"Prairie", "Praise", "Prance", "Pravda", "Prayer", "Preach",
"Preachy", "Precede", "Precept", "Precess", "Precis", "Precise",
"Predict", "Preempt", "Prefab", "Preface", "Prefect", "Prefer",
"Prefix", "Prelude", "Premier", "Premise", "Premium", "Prepare",
"Presage", "Present", "Preside", "Presto", "Preston", "Presume",
"Pretend", "Pretext", "Pretty", "Prevail", "Prevent", "Preview",
"Prickle", "Priest", "Primacy", "Primal", "Primary", "Primate",
"Prince", "Priori", "Priory", "Prison", "Prissy", "Privacy",
"Private", "Privet", "Probate", "Probity", "Problem", "Proceed",
"Process", "Procter", "Proctor", "Procure", "Procyon", "Prodigy",
"Produce", "Product", "Profane", "Profess", "Proffer", "Profile",
"Profit", "Profuse", "Progeny", "Project", "Prolate", "Proline",
"Prolix", "Prolong", "Promise", "Promote", "Prompt", "Pronoun",
"Pronto", "Propane", "Propel", "Proper", "Prophet", "Propos",
"Propose", "Propyl", "Prorate", "Prosaic", "Prosody", "Prosper",
"Protean", "Protect", "Protege", "Protein", "Protest", "Proton",
"Proust", "Proven", "Proverb", "Provide", "Proviso", "Provoke",
"Provost", "Prowess", "Prudent", "Prussia", "Psalter", "Pseudo",
"Psyche", "Psychic", "Psycho", "Ptolemy", "Puberty", "Public",
"Publish", "Puccini", "Puckish", "Pudding", "Puddle", "Puddly",
"Pueblo", "Puerile", "Puerto", "Puffed", "Puffery", "Puffin",
"Pulaski", "Pulley", "Pullman", "Pulpit", "Pulsar", "Pulsate",
"Pumice", "Pummel", "Pumpkin", "Pundit", "Pungent", "Punish",
"Punster", "Pupate", "Puppet", "Purcell", "Purdue", "Purify",
"Purina", "Purine", "Puritan", "Purloin", "Purple", "Purport",
"Purpose", "Pursue", "Pursuer", "Pursuit", "Purvey", "Purview",
"Pushout", "Pushpin", "Putnam", "Puzzle", "Pyhrric", "Pyramid",
"Pyrite", "Pyrrhic", "Pyrrhic", "Python", "Quadric", "Quahog",
"Quaint", "Qualify", "Quality", "Quanta", "Quantum", "Quarrel",
"Quarry", "Quartet", "Quartic", "Quartz", "Quasar", "Quaver",
"Queasy", "Quebec", "Quench", "Quetzal", "Quezon", "Quibble",
"Quicken", "Quickie", "Quietus", "Quince", "Quinine", "Quintet",
"Quintic", "Quintus", "Quirky", "Quiver", "Quixote", "Quizzes",
"Quonset", "Quorum", "Rabbet", "Rabbit", "Rabble", "Rabies",
"Raccoon", "Raceway", "Rachel", "Racial", "Racket", "Rackety",
"Radial", "Radian", "Radiant", "Radiate", "Radical", "Radices",
"Radish", "Radium", "Radius", "Rafael", "Raffia", "Raffish",
"Raffle", "Ragging", "Ragout", "Ragweed", "Railway", "Rainbow",
"Raisin", "Rakish", "Raleigh", "Ralston", "Ramada", "Ramble",
"Ramify", "Rampage", "Rampant", "Rampart", "Ramrod", "Ramsey",
"Rancho", "Rancid", "Randall", "Random", "Rangoon", "Ranier",
"Rankin", "Rankine", "Rankle", "Ransack", "Ransom", "Raphael",
"Rapier", "Rapport", "Rapture", "Rarefy", "Raritan", "Rascal",
"Raster", "Rastus", "Rather", "Ratify", "Rattail", "Rattle",
"Raucous", "Ravage", "Ravine", "Ravish", "Rawhide", "Raymond",
"Razzle", "Readout", "Reagan", "Realtor", "Realty", "Reason",
"Rebecca", "Rebuke", "Receipt", "Receive", "Recent", "Recess",
"Recife", "Recipe", "Recital", "Reckon", "Recline", "Recluse",
"Recruit", "Rectify", "Rector", "Rectory", "Recuse", "Redact",
"Redbird", "Redbud", "Redcoat", "Redden", "Reddish", "Redhead",
"Redmond", "Redneck", "Redound", "Redpoll", "Redtop", "Reduce",
"Redwood", "Reeves", "Referee", "Reflect", "Refract", "Refrain",
"Refuge", "Refugee", "Refusal", "Refute", "Regale", "Regalia",
"Regard", "Regatta", "Regent", "Regime", "Regimen", "Regina",
"Region", "Regress", "Regret", "Regular", "Regulus", "Reilly",
"Reject", "Rejoice", "Relate", "Relayed", "Reliant", "Relict",
"Relief", "Relieve", "Relish", "Remand", "Remark", "Remedy",
"Remiss", "Remnant", "Remorse", "Remote", "Removal", "Renault",
"Render", "Renewal", "Renoir", "Renown", "Rental", "Repeal",
"Repeat", "Repent", "Replete", "Replica", "Report", "Reprise",
"Reptile", "Repute", "Request", "Require", "Reredos", "Rescind",
"Rescue", "Resent", "Reserve", "Reside", "Residue", "Resign",
"Resiny", "Resist", "Resolve", "Resort", "Respect", "Respire",
"Respite", "Respond", "Restful", "Restive", "Result", "Resume",
"Retail", "Retain", "Retard", "Retina", "Retinal", "Retinue",
"Retire", "Retiree", "Retort", "Retract", "Return", "Reuben",
"Reuters", "Reveal", "Revelry", "Revenge", "Revenue", "Revere",
"Reverie", "Reverse", "Revert", "Revery", "Revile", "Revisal",
"Revise", "Revival", "Revive", "Revoke", "Revolt", "Revolve",
"Revved", "Revving", "Reward", "Rhenish", "Rhenium", "Rhesus",
"Rhodes", "Rhodium", "Rhombi", "Rhombic", "Rhombus", "Rhubarb",
"Rhythm", "Ribald", "Ribbon", "Ribose", "Richard", "Richter",
"Rickets", "Rickety", "Ridden", "Riddle", "Ridgway", "Riemann",
"Riffle", "Rigging", "Ringlet", "Riordan", "Riotous", "Ripley",
"Ripoff", "Ripple", "Risible", "Ritchie", "Ritter", "Ritual",
"Rivalry", "Riviera", "Rivulet", "Riyadh", "Roadbed", "Roadway",
"Robbery", "Robbin", "Robbins", "Robert", "Roberta", "Roberto",
"Roberts", "Robotic", "Robust", "Rocket", "Rockies", "Rococo",
"Rodent", "Rodgers", "Rodney", "Roebuck", "Rogers", "Roister",
"Roland", "Rollick", "Rollins", "Romance", "Romania", "Romano",
"Romulus", "Ronald", "Ronnie", "Rooftop", "Rookie", "Roomful",
"Rosalie", "Rosary", "Rosebud", "Rosetta", "Rosette", "Roster",
"Rostrum", "Rotary", "Rotate", "Rotten", "Rotund", "Rotunda",
"Roughen", "Roundup", "Routine", "Rowboat", "Rowena", "Rowland",
"Rowley", "Roxbury", "Royalty", "Ruanda", "Rubbery", "Rubbish",
"Rubble", "Rubdown", "Rubric", "Ruckus", "Rudder", "Rudolf",
"Rudolph", "Rudyard", "Rueful", "Ruffian", "Ruffle", "Rufous",
"Ruinous", "Rumania", "Rumble", "Rumford", "Rummage", "Rumple",
"Rumpus", "Runaway", "Rundown", "Runneth", "Runoff", "Runway",
"Runyon", "Rupture", "Russell", "Russet", "Russia", "Russula",
"Rustic", "Rustle", "Rutgers", "Rutile", "Rutland", "Rwanda",
"Rydberg", "Sabbath", "Sabina", "Sabine", "Saccade", "Sachem",
"Sacral", "Sacred", "Sadden", "Saddle", "Sadism", "Sadist", "Sadler",
"Safari", "Safety", "Saffron", "Sagging", "Saginaw", "Saguaro",
"Sahara", "Saigon", "Sailor", "Salaam", "Salami", "Salary",
"Salerno", "Salient", "Salina", "Saline", "Salish", "Saliva",
"Sallow", "Salmon", "Saloon", "Salsify", "Salute", "Salvage",
"Samovar", "Sample", "Sampson", "Samson", "Samuel", "Sanborn",
"Sanchez", "Sancho", "Sandal", "Sandbag", "Sanders", "Sandia",
"Sandman", "Sandra", "Sanford", "Sanicle", "Sapiens", "Sapient",
"Sapling", "Saracen", "Sarcasm", "Sarcoma", "Sardine", "Sargent",
"Sashay", "Satanic", "Satiate", "Satiety", "Satire", "Satiric",
"Satisfy", "Saturn", "Sausage", "Savage", "Savant", "Saviour",
"Sawdust", "Sawfish", "Sawfly", "Sawmill", "Sawyer", "Saxony",
"Scalar", "Scallop", "Scandal", "Scanty", "Scapula", "Scarce",
"Scarify", "Scarlet", "Scarves", "Scathe", "Scenery", "Scenic",
"Sceptic", "Schafer", "Schantz", "Schema", "Scheme", "Scherzo",
"Schism", "Schist", "Schlitz", "Schloss", "Schmidt", "Schmitt",
"Scholar", "School", "Schultz", "Schulz", "Schwab", "Science",
"Scissor", "Scopic", "Scorch", "Scoria", "Scorpio", "Scotch",
"Scotia", "Scotty", "Scourge", "Scrape", "Scratch", "Scrawl",
"Scrawny", "Scream", "Screech", "Screed", "Screen", "Scribe",
"Scripps", "Script", "Scriven", "Scroll", "Scrooge", "Scrotum",
"Scruple", "Scuffle", "Sculpin", "Sculpt", "Scurry", "Scurvy",
"Scuttle", "Scutum", "Scylla", "Scythe", "Scythia", "Seafare",
"Seafood", "Seagram", "Seagull", "Sealant", "Seaman", "Seamen",
"Seance", "Seaport", "Search", "Seaside", "Season", "Seater",
"Seattle", "Seaward", "Seaweed", "Secant", "Secede", "Seclude",
"Second", "Secrecy", "Secret", "Secrete", "Section", "Sector",
"Secular", "Secure", "Sedate", "Seduce", "Seeable", "Seedbed",
"Seeing", "Seepage", "Seethe", "Seethed", "Segment", "Segovia",
"Segundo", "Seidel", "Seismic", "Seizure", "Seldom", "Select",
"Selena", "Selfish", "Selkirk", "Seller", "Sellout", "Seltzer",
"Selves", "Selwyn", "Seminal", "Seminar", "Semite", "Semitic",
"Semper", "Senate", "Seneca", "Senegal", "Senile", "Senior",
"Senora", "Sensate", "Sensor", "Sensory", "Sensual", "Sentry",
"Septate", "Septic", "Septum", "Sequel", "Sequent", "Sequin",
"Sequoia", "Serape", "Serbia", "Serene", "Serfdom", "Sergei",
"Serial", "Seriate", "Series", "Serine", "Serious", "Sermon",
"Serpens", "Serpent", "Servant", "Service", "Servile", "Sesame",
"Session", "Setback", "Settle", "Seventh", "Seventy", "Several",
"Severe", "Severn", "Seville", "Sewage", "Seward", "Sextans",
"Sextet", "Sexton", "Sexual", "Seymour", "Shabby", "Shackle",
"Shadow", "Shadowy", "Shafer", "Shaffer", "Shaggy", "Shaken",
"Shallot", "Shallow", "Shalom", "Shamble", "Shampoo", "Shannon",
"Shanty", "Shapiro", "Sharon", "Sharpe", "Sharpen", "Shasta",
"Shatter", "Shaven", "Shawnee", "Shearer", "Sheath", "Sheathe",
"Sheave", "Shedir", "Sheehan", "Sheila", "Shelby", "Sheldon",
"Shelley", "Shelter", "Shelton", "Shelve", "Shepard", "Sherbet",
"Sheriff", "Sherman", "Sherry", "Sherwin", "Shield", "Shields",
"Shifty", "Shiloh", "Shimmy", "Shingle", "Shinto", "Shiplap",
"Shipley", "Shipman", "Shipmen", "Shirley", "Shiver", "Shivery",
"Shmuel", "Shoddy", "Shoofly", "Shorten", "Shotgun", "Should",
"Shovel", "Showman", "Showmen", "Shrank", "Shrewd", "Shriek",
"Shrift", "Shrike", "Shrill", "Shrilly", "Shrimp", "Shrine",
"Shrink", "Shrive", "Shrivel", "Shroud", "Shrove", "Shrunk",
"Shudder", "Shuffle", "Shulman", "Shutoff", "Shutout", "Shuttle",
"Shylock", "Siamese", "Siberia", "Sibley", "Sibling", "Sicily",
"Sicken", "Sickish", "Sickle", "Sidearm", "Sidecar", "Sideman",
"Sidemen", "Sideway", "Sidney", "Siegel", "Siemens", "Sienna",
"Sierra", "Siesta", "Sigmund", "Signal", "Signet", "Signify",
"Signor", "Signora", "Silage", "Silane", "Silent", "Silica",
"Silicic", "Silicon", "Silken", "Silver", "Silvery", "Similar",
"Simile", "Simmer", "Simmons", "Simons", "Simper", "Simple",
"Simplex", "Simply", "Simpson", "Sincere", "Sinewy", "Sinful",
"Single", "Singlet", "Sinter", "Sinuous", "Sirius", "Siskin",
"Sister", "Sistine", "Situate", "Sixfold", "Sixgun", "Sixteen",
"Sizzle", "Skater", "Skeptic", "Sketch", "Sketchy", "Skiddy",
"Skillet", "Skimpy", "Skinny", "Skippy", "Skittle", "Skopje",
"Skyhook", "Skyjack", "Skylark", "Skyline", "Skyward", "Skywave",
"Skyway", "Slacken", "Sladang", "Slander", "Slater", "Slavery",
"Slavic", "Slavish", "Sledge", "Sleepy", "Sleety", "Sleeve",
"Sleigh", "Sleight", "Slender", "Sleuth", "Slight", "Slither",
"Sliver", "Slivery", "Sloane", "Slocum", "Slogan", "Sloppy",
"Slouch", "Slough", "Sloven", "Sludge", "Sluice", "Slumber",
"Slurry", "Smaller", "Smalley", "Smatter", "Smithy", "Smitten",
"Smolder", "Smooch", "Smooth", "Smother", "Smucker", "Smudge",
"Smudgy", "Smuggle", "Smutty", "Smyrna", "Smythe", "Snappy",
"Snatch", "Snazzy", "Sneaky", "Sneeze", "Snider", "Sniffle",
"Sniffly", "Snifter", "Snigger", "Snippet", "Snippy", "Snivel",
"Snoopy", "Snorkel", "Snotty", "Snuffer", "Snuffle", "Snuffly",
"Snuggle", "Snuggly", "Snyder", "Soapsud", "Soccer", "Social",
"Societe", "Society", "Socket", "Sockeye", "Sodden", "Sodium",
"Soffit", "Soften", "Soignee", "Soiree", "Sojourn", "Solace",
"Solder", "Soldier", "Solemn", "Solicit", "Solidus", "Soliton",
"Solomon", "Soluble", "Solute", "Solvate", "Solvent", "Somali",
"Somatic", "Somber", "Sombre", "Someday", "Somehow", "Someone",
"Somers", "Sonant", "Sonata", "Songbag", "Songful", "Sonnet",
"Sonoma", "Sonora", "Soothe", "Sophia", "Sophia", "Sophie",
"Sophism", "Soprano", "Sorcery", "Sordid", "Sorghum", "Sorrel",
"Sorrow", "Sortie", "Souffle", "Sought", "Soulful", "Source",
"Soutane", "Southey", "Soviet", "Sovkhoz", "Soybean", "Spangle",
"Spaniel", "Spanish", "Sparge", "Sparkle", "Sparky", "Sparrow",
"Sparse", "Sparta", "Spartan", "Spastic", "Spatial", "Spatlum",
"Spatula", "Spavin", "Spayed", "Special", "Specie", "Species",
"Specify", "Speckle", "Spector", "Spectra", "Speech", "Speedup",
"Speedy", "Spencer", "Sperry", "Sphere", "Spheric", "Sphinx",
"Spider", "Spidery", "Spiegel", "Spigot", "Spinach", "Spinal",
"Spindle", "Spinoff", "Spiral", "Spirit", "Spittle", "Splash",
"Splashy", "Splayed", "Spleen", "Splice", "Spline", "Splint",
"Splotch", "Splurge", "Spokane", "Spoken", "Sponge", "Spongy",
"Sponsor", "Spooky", "Sporty", "Spotty", "Spouse", "Sprague",
"Sprain", "Sprang", "Sprawl", "Spread", "Spring", "Springe",
"Springy", "Sprint", "Sprite", "Sproul", "Sprout", "Spruce",
"Sprung", "Spumoni", "Spurge", "Sputnik", "Sputter", "Squalid",
"Squall", "Square", "Squash", "Squashy", "Squawk", "Squeak",
"Squeaky", "Squeal", "Squeeze", "Squelch", "Squibb", "Squill",
"Squint", "Squire", "Squirm", "Squirmy", "Squirt", "Squishy",
"Stabile", "Stable", "Stadia", "Stadium", "Staley", "Stalin",
"Stamen", "Stamina", "Stammer", "Stance", "Stanch", "Standby",
"Stanley", "Stannic", "Stanton", "Stanza", "Staple", "Starch",
"Starchy", "Stardom", "Starkey", "Starlet", "Startle", "Startup",
"Starve", "Stasis", "Staten", "Stater", "Static", "Statler",
"Stator", "Statue", "Stature", "Status", "Statute", "Staunch",
"Stayed", "Steady", "Stealth", "Steamy", "Stearic", "Stearns",
"Steele", "Steely", "Steepen", "Steeple", "Steeve", "Stefan",
"Steiner", "Stella", "Stella", "Stellar", "Stench", "Stencil",
"Stephen", "Steppe", "Stepson", "Stereo", "Sterile", "Sternal",
"Sterno", "Sternum", "Steroid", "Stetson", "Steuben", "Steven",
"Stevens", "Steward", "Stewart", "Stickle", "Sticky", "Stiffen",
"Stifle", "Stigma", "Stimuli", "Stingy", "Stinky", "Stipend",
"Stipple", "Stirrup", "Stitch", "Stocky", "Stodgy", "Stokes",
"Stolen", "Stolid", "Stomach", "Stooge", "Stopgap", "Storage",
"Storey", "Stormy", "Stowage", "Strafe", "Strain", "Strait",
"Strand", "Strange", "Strata", "Stratum", "Strauss", "Streak",
"Stream", "Street", "Stress", "Stretch", "Strewn", "Striate",
"Strict", "Stride", "Strife", "Strike", "String", "Stringy",
"Stripe", "Stripy", "Strive", "Striven", "Strobe", "Strode",
"Stroke", "Stroll", "Strong", "Strophe", "Strove", "Struck",
"Strung", "Stuart", "Stubble", "Stubby", "Stucco", "Student",
"Studio", "Stuffy", "Stumble", "Stumpy", "Stupefy", "Stupid",
"Stupor", "Sturdy", "Stutter", "Stygian", "Stylish", "Stylus",
"Stymie", "Styrene", "Subject", "Submit", "Subsidy", "Subsist",
"Subsume", "Subtle", "Subtly", "Suburb", "Subvert", "Succeed",
"Success", "Succumb", "Sucrose", "Suction", "Sudden", "Suffer",
"Suffice", "Suffix", "Suffolk", "Suffuse", "Suggest", "Suicide",
"Suitor", "Sulfate", "Sulfide", "Sulfite", "Sulfur", "Sullen",
"Sulphur", "Sultan", "Sultry", "Sumatra", "Sumeria", "Summand",
"Summary", "Summate", "Summers", "Summit", "Summon", "Sumner",
"Sumter", "Sunbeam", "Sunburn", "Sunday", "Sunder", "Sundew",
"Sundial", "Sundown", "Sundry", "Sunfish", "Sunken", "Sunlit",
"Sunrise", "Sunset", "Sunspot", "Suntan", "Superb", "Supine",
"Supple", "Supply", "Support", "Suppose", "Supreme", "Surety",
"Surface", "Surfeit", "Surgeon", "Surgery", "Surmise", "Surname",
"Surpass", "Surplus", "Surreal", "Surrey", "Surtax", "Surtout",
"Survey", "Survive", "Susanne", "Suspect", "Suspend", "Sussex",
"Sustain", "Sutton", "Suture", "Suzanne", "Suzuki", "Svelte",
"Swabby", "Swahili", "Swallow", "Swampy", "Swanky", "Swanson",
"Swarthy", "Swatch", "Swathe", "Sweater", "Sweaty", "Sweden",
"Swedish", "Sweeney", "Sweeten", "Swelter", "Swenson", "Swerve",
"Swindle", "Swingy", "Swirly", "Swishy", "Switch", "Switzer",
"Swivel", "Swizzle", "Swollen", "Sydney", "Syenite", "Syllabi",
"Sylvan", "Sylvia", "Symbol", "Symptom", "Synapse", "Syndic",
"Synergy", "Synonym", "Syntax", "Syringa", "Syringe", "Syrinx",
"Syrupy", "System", "Syzygy", "Szilard", "Tableau", "Tablet",
"Tabloid", "Tabula", "Tabular", "Tacitus", "Tackle", "Tacoma",
"Tactful", "Tactic", "Tactile", "Tactual", "Tadpole", "Taffeta",
"Tagging", "Tahiti", "Tailor", "Taipei", "Taiwan", "Takeoff",
"Taketh", "Talcum", "Talent", "Talkie", "Tallow", "Tallyho",
"Talmud", "Tamale", "Tammany", "Tampon", "Tanager", "Tanaka",
"Tandem", "Tangent", "Tangle", "Tannin", "Tantrum", "Taoist",
"Tappet", "Tarbell", "Target", "Tariff", "Tarnish", "Tarpon",
"Tartar", "Tartary", "Tarzan", "Tassel", "Tasting", "Tattle",
"Tattler", "Tattoo", "Taught", "Taurus", "Tavern", "Taverna",
"Tawdry", "Taxicab", "Taxied", "Taxiway", "Taylor", "Teacart",
"Teacup", "Teapot", "Tearful", "Teasel", "Technic", "Tedious",
"Tedium", "Teeing", "Teenage", "Teensy", "Teeter", "Teethe",
"Teethed", "Teflon", "Teheran", "Tehran", "Tektite", "Teleost",
"Teller", "Temper", "Tempera", "Tempest", "Temple", "Tenable",
"Tenant", "Tendon", "Tenfold", "Tenneco", "Tenney", "Tennis",
"Tensile", "Tension", "Tensor", "Tenspot", "Tenuous", "Tenure",
"Terbium", "Tercel", "Teresa", "Termini", "Termite", "Ternary",
"Terrace", "Terrain", "Terrier", "Terrify", "Terror", "Testate",
"Testbed", "Testes", "Testify", "Tetanus", "Tether", "Texaco",
"Textile", "Textron", "Textual", "Texture", "Thalia", "Thatch",
"Thayer", "Thebes", "Theism", "Theist", "Thelma", "Thence",
"Theorem", "Theory", "Therapy", "Thereat", "Thereby", "Therein",
"Thereof", "Thereon", "Theresa", "Thereto", "Thermal", "Thermo",
"Theses", "Theseus", "Thesis", "Thetis", "Thiamin", "Thicken",
"Thicket", "Thieves", "Thimble", "Thimbu", "Thirst", "Thirsty",
"Thirty", "Thistle", "Thither", "Thomas", "Thomson", "Thoreau",
"Thorium", "Thorny", "Thorpe", "Though", "Thought", "Thrall",
"Thrash", "Thread", "Threat", "Thresh", "Thrice", "Thrift",
"Thrifty", "Thrill", "Thrips", "Thrive", "Throat", "Throaty",
"Throes", "Throne", "Throng", "Through", "Thrown", "Thrush",
"Thrust", "Thruway", "Thuban", "Thuggee", "Thulium", "Thunder",
"Thurman", "Thwack", "Thwart", "Thymine", "Thymus", "Thyroid",
"Tibetan", "Ticket", "Tickle", "Tidbit", "Tiffany", "Tighten",
"Tigress", "Tigris", "Timber", "Timbre", "Timeout", "Timothy",
"Tinder", "Tinfoil", "Tingle", "Tinker", "Tinkle", "Tinsel",
"Tintype", "Tipoff", "Tipple", "Tiptoe", "Tirade", "Tirana",
"Tissue", "Titanic", "Titian", "Titrate", "Titular", "Tobacco",
"Tobago", "Toccata", "Toddle", "Toenail", "Toffee", "Togging",
"Toggle", "Toilet", "Tokamak", "Toledo", "Tolstoy", "Toluene",
"Tomato", "Tommie", "Tongue", "Tonight", "Tonnage", "Tonsil",
"Toodle", "Toolkit", "Tootle", "Topcoat", "Topeka", "Topmost",
"Topple", "Topsoil", "Tornado", "Toroid", "Toronto", "Torpedo",
"Torpid", "Torpor", "Torque", "Torrent", "Torrid", "Torsion",
"Torture", "Toshiba", "Totemic", "Touchy", "Tousle", "Toward",
"Towboat", "Towhead", "Towhee", "Toyota", "Tracery", "Trachea",
"Tractor", "Traffic", "Tragedy", "Tragic", "Trainee", "Traipse",
"Traitor", "Trammel", "Trample", "Tramway", "Trance", "Transit",
"Transom", "Trashy", "Trauma", "Travail", "Travel", "Travis",
"Treadle", "Treason", "Treaty", "Treble", "Treetop", "Trefoil",
"Trellis", "Tremble", "Tremor", "Trench", "Trendy", "Trenton",
"Trestle", "Triable", "Trianon", "Tribal", "Tribune", "Tribute",
"Trickle", "Tricky", "Trident", "Trifle", "Trigram", "Trilogy",
"Trimer", "Trinity", "Trinket", "Triode", "Triple", "Triplet",
"Triplex", "Tripod", "Tripoli", "Tristan", "Tritium", "Triton",
"Triumph", "Triune", "Trivia", "Trivial", "Trivium", "Trodden",
"Troika", "Trojan", "Trolley", "Trollop", "Trompe", "Trophic",
"Trophy", "Tropic", "Trouble", "Trough", "Trounce", "Troupe",
"Trouser", "Truancy", "Truant", "Trudge", "Truism", "Truman",
"Trumpet", "Trundle", "Trustee", "Trypsin", "Tsarina", "Tsunami",
"Tubular", "Tubule", "Tucker", "Tucson", "Tuesday", "Tugging",
"Tuition", "Tulane", "Tumble", "Tumbrel", "Tumult", "Tundra",
"Tuneful", "Tunisia", "Tunnel", "Tupelo", "Turban", "Turbid",
"Turbine", "Turgid", "Turing", "Turkey", "Turkish", "Turmoil",
"Turnery", "Turnip", "Turnkey", "Turnoff", "Turnout", "Turret",
"Turtle", "Tuscan", "Tuscany", "Tussle", "Tuttle", "Tuxedo",
"Twaddle", "Tweedy", "Tweeze", "Twelfth", "Twelve", "Twenty",
"Twiddle", "Twinge", "Twinkle", "Twirly", "Twisty", "Twitch",
"Twitchy", "Twofold", "Twombly", "Twosome", "Tyburn", "Tycoon",
"Tyndall", "Typeset", "Typhoid", "Typhon", "Typhoon", "Typhus",
"Typify", "Tyranny", "Tyrant", "Uganda", "Ukraine", "Ullman",
"Ulster", "Ulysses", "Umbrage", "Umlaut", "Umpire", "Uncouth",
"Unction", "Unesco", "Unicorn", "Uniform", "Uniplex", "Unique",
"Unisex", "Unison", "Unital", "Unitary", "Univac", "Unkempt",
"Unruly", "Upbeat", "Upbraid", "Upbring", "Upcome", "Update",
"Updraft", "Upgrade", "Upheld", "Uphill", "Uphold", "Upkeep",
"Upland", "Uplift", "Upraise", "Upright", "Uprise", "Upriver",
"Uproar", "Uproot", "Upshot", "Upside", "Upsilon", "Upslope",
"Upstair", "Upstand", "Upstart", "Upstate", "Upsurge", "Upswing",
"Uptake", "Uptown", "Uptrend", "Upturn", "Upward", "Upwind",
"Uracil", "Urania", "Uranium", "Uranus", "Uranyl", "Urbana",
"Urbane", "Urchin", "Uremia", "Urethra", "Urgency", "Urgent",
"Urging", "Urinal", "Urinary", "Ursula", "Uruguay", "Usable",
"Useful", "Usurer", "Utensil", "Uterine", "Uterus", "Utility",
"Utmost", "Utopia", "Utopian", "Utrecht", "Vacant", "Vacate",
"Vaccine", "Vacuole", "Vacuous", "Vacuum", "Vagary", "Vagrant",
"Valent", "Valerie", "Valery", "Valeur", "Valiant", "Valine",
"Valley", "Valois", "Valuate", "Vampire", "Vandal", "Vanilla",
"Vanish", "Vanity", "Vantage", "Variac", "Varian", "Variant",
"Variate", "Variety", "Various", "Varnish", "Varsity", "Vasquez",
"Vassal", "Vassar", "Vatican", "Vaudois", "Vaughan", "Vaughn",
"Vector", "Vehicle", "Vellum", "Velours", "Velvet", "Velvety",
"Vendor", "Veneer", "Veneto", "Venial", "Venice", "Venison",
"Venous", "Venture", "Venturi", "Veranda", "Verbal", "Verbena",
"Verbose", "Verdant", "Verdict", "Veridic", "Verify", "Verity",
"Verlag", "Vermeil", "Vermin", "Vermont", "Vernal", "Vernier",
"Vernon", "Verona", "Version", "Versus", "Vertex", "Vertigo",
"Vesper", "Vessel", "Vestal", "Vestige", "Vestry", "Veteran",
"Viaduct", "Vibrant", "Vibrate", "Vibrato", "Viceroy", "Vicinal",
"Vicious", "Victim", "Victor", "Victory", "Victual", "Vienna",
"Vietnam", "Viking", "Vilify", "Village", "Villain", "Villein",
"Vincent", "Vinegar", "Vinson", "Vintage", "Vintner", "Violate",
"Violent", "Violet", "Violin", "Virgil", "Virgin", "Virgule",
"Virile", "Virtual", "Virtue", "Visage", "Viscera", "Viscous",
"Vishnu", "Visible", "Vision", "Visitor", "Visual", "Vitamin",
"Vitiate", "Vitrify", "Vitriol", "Vivace", "Vivaldi", "Vivian",
"Vivify", "Vocable", "Vocalic", "Vocate", "Volcano", "Volley",
"Voltage", "Voltaic", "Voluble", "Volume", "Voodoo", "Vortex",
"Votary", "Votive", "Vought", "Voyage", "Vulcan", "Vulgar",
"Vulpine", "Vulture", "Wabash", "Waddle", "Waffle", "Wagging",
"Waggle", "Wagner", "Wakeful", "Wakeup", "Walcott", "Walden",
"Waldorf", "Waldron", "Walkie", "Walkout", "Walkway", "Wallaby",
"Wallace", "Waller", "Wallet", "Wallis", "Wallop", "Wallow",
"Walnut", "Walpole", "Walrus", "Walter", "Walters", "Waltham",
"Walton", "Wander", "Wangle", "Wanton", "Wapato", "Wapiti", "Warble",
"Warden", "Warfare", "Warhead", "Waring", "Warlike", "Warmish",
"Warmth", "Warmup", "Warrant", "Warren", "Warrior", "Warsaw",
"Wartime", "Warwick", "Washout", "Waspish", "Wastage", "Wastrel",
"Waters", "Watery", "Watkins", "Watson", "Wattage", "Wattle",
"Wavelet", "Waxwork", "Waybill", "Waylaid", "Waylay", "Wayside",
"Wayward", "Weaken", "Wealth", "Wealthy", "Weapon", "Wearied",
"Weasel", "Weather", "Webster", "Wedlock", "Weekday", "Weekend",
"Weight", "Weighty", "Welcome", "Weldon", "Welfare", "Weller",
"Welles", "Wendell", "Werner", "Werther", "Wesley", "Western",
"Weston", "Wetland", "Whalen", "Wharton", "Wharves", "Whatley",
"Whatnot", "Wheedle", "Wheeze", "Wheezy", "Whelan", "Wheller",
"Whence", "Whereas", "Whereby", "Wherein", "Whereof", "Whereon",
"Whether", "Whimper", "Whimsey", "Whimsic", "Whinny", "Whippet",
"Whipple", "Whipsaw", "Whisper", "Whistle", "Whiten", "Whither",
"Whitman", "Whitney", "Whittle", "Whoever", "Wholly", "Whoosh",
"Wichita", "Wicket", "Widgeon", "Widget", "Wiener", "Wigging",
"Wiggins", "Wiggle", "Wiggly", "Wigmake", "Wigwam", "Wilbur",
"Wilcox", "Wildcat", "Wilfred", "Wilful", "Wilhelm", "Wilkes",
"Wilkie", "Wilkins", "Willard", "Willful", "William", "Willie",
"Willis", "Willow", "Willowy", "Wilson", "Windbag", "Window",
"Windsor", "Windup", "Winery", "Wingman", "Wingmen", "Wingtip",
"Winkle", "Winnie", "Winnow", "Winslow", "Winsome", "Winston",
"Winter", "Winters", "Wintry", "Wireman", "Wiremen", "Wiretap",
"Wisdom", "Wishful", "Wistful", "Withal", "Wither", "Within",
"Without", "Witness", "Wizard", "Wobble", "Woeful", "Wolcott",
"Wolfish", "Wolves", "Wombat", "Wonder", "Woodard", "Woodcut",
"Wooden", "Woodhen", "Woodlot", "Woodrow", "Woodrow", "Wooster",
"Workday", "Workman", "Workmen", "Workout", "Worsen", "Worship",
"Worthy", "Wraith", "Wrangle", "Wrapup", "Wreath", "Wreathe",
"Wrench", "Wrestle", "Wretch", "Wriggle", "Wright", "Wrigley",
"Wrinkle", "Writeup", "Writhe", "Written", "Wrongdo", "Wrought",
"Wyoming", "Xavier", "Xerxes", "Xylene", "Yakima", "Yamaha",
"Yankee", "Yankton", "Yaounde", "Yapping", "Yardage", "Yarrow",
"Yeager", "Yeasty", "Yellow", "Yeoman", "Yerkes", "Yeshiva",
"Yiddish", "Yipping", "Yoghurt", "Yogurt", "Yokuts", "Yonkers",
"Yttrium", "Yucatan", "Yvette", "Zachary", "Zagging", "Zagreb",
"Zambia", "Zealand", "Zealot", "Zealous", "Zenith", "Zeroes",
"Zeroth", "Ziegler", "Zigging", "Zigzag", "Zionism", "Zircon",
"Zodiac", "Zombie", "Zoology", "Zounds", "Zurich", "Zygote" };

const char *games[6] = { "Morning", "Evening", "Afternoon", "Championship", "Novice", "299er" };

main(int argc, char **argv)
{
  int minp, maxp, minb, maxb, i, h, np, nb, rn, j, k;
  char s[1000];
  SVec p;
  string nm;
  ifstream is;
  SSVec scores;
  SSVec mps;
  SVec tmps;
  SSVec boards;
  SSVec bmps;
  istringstream ss;
  DVec pscores, tplayed, perc, sperc;
  double top, d;
  string empty;
  int format;
  int winner, bfirst;
  int second;
  double mp1;
  double mp2;
  double mp3;

  if (argc != 8) {
    cerr << "usage: gen_printout header(0|1) score_file minp maxp minb maxb top\n";
    exit(1);
  }

  srand48(time(0));

  format = lrand48()%3;
  winner = (lrand48()%5 == 0);
  second = (winner && lrand48()%5 == 0);
  mp1 = drand48()+.5*2;
  mp2 = mp1 * .8;
  mp3 = mp1 * .6;
  bfirst = lrand48()%2;

  h = atoi(argv[1]);
  minp = atoi(argv[3]);
  maxp = atoi(argv[4]);
  minb = atoi(argv[5]);
  maxb = atoi(argv[6]);
  i = atoi(argv[7]);
  top = i;

  rn = lrand48()%10000;
  np = minp + lrand48()%(maxp-minp+1);
  nb = minb + lrand48()%(maxb-minb+1);

  sprintf(s, "random_names %d > tmp-%d.txt", np*6, rn);
  (void) system(s);

  sprintf(s, "tmp-%d.txt", rn);
  is.open(s);
  while (getline(is, nm)) p.push_back(nm);
  is.clear();
  is.close();
  
  if (lrand48()%2) { j = lrand48()%4; for (i = 0; i <= j; i++) { k = lrand48()%30; while (k-- > 0) printf("-"); printf(","); } printf("\n"); }

  printf("%s %s Bridge Club %s%s Game\n", lns[lrand48()%7908], lns[lrand48()%7908], 
    lrand48()%2 ? "---" : "                   ", games[lrand48()%6]);

  if (lrand48()%2) { j = lrand48()%4; for (i = 0; i <= j; i++) { k = lrand48()%30; while (k-- > 0) printf("-"); printf(","); } printf("\n"); }
  
  if (lrand48()%2) {
    printf("%s - Director\n", p[np*2+1].c_str());
  } else {
    printf("Director: %s \n", p[np*2+1].c_str());
  }
  if (lrand48()%2) { j = lrand48()%4; for (i = 0; i <= j; i++) { k = lrand48()%30; while (k-- > 0) printf("-"); printf(","); } printf("\n"); }
  if (lrand48()%2) printf("----- Unit %ld", lrand48()%900+100);
  if (lrand48()%2) printf(" ----- Club %ld", lrand48()%90000+10000);
  j = lrand48()%6;
  if (lrand48()%2) printf(" ----- Division %c", 'A' + j);
  printf("\n");
  if (lrand48()%2) { j = lrand48()%4; for (i = 0; i <= j; i++) { k = lrand48()%30; while (k-- > 0) printf("-"); printf(","); } printf("\n"); }

  printf("\nPLAYERS\n\n");
  
  sprintf(s, "rm tmp-%d.txt", rn);
  (void) system(s);
  
  is.open(argv[2]);
  
  while (is >> nm) {
    if (nm == "ENDSCORE") {
      scores.push_back(tmps);
      tmps.clear();
    } else if (nm == "ENDMP") {
      mps.push_back(tmps);
      tmps.clear();
    } else tmps.push_back(nm);
  }
     
  pscores.resize(np, 0);
  tplayed.resize(np, 0);
  

  boards.resize(nb);
  VIT(i, boards) FUP(j, np) boards[i].push_back("Fred");
  bmps.resize(nb);
  VIT(i, bmps) FUP(j, np) bmps[i].push_back("Fred");


  FUP(i, nb) {
    rn = lrand48()%scores.size();
    VIT(j, scores[rn]) {
      
      do k = (lrand48()%scores[rn].size()+(i/2))%np; while (boards[i][k] != "Fred");
      boards[i][k] = scores[rn][j];
      bmps[i][k] = mps[rn][j];
    }
  }

  switch(lrand48()%3) {
    case 0: i = '-'; break;
    case 1: i = 'x'; break;
    case 2: i = '_'; break;
  }

  empty.push_back(i);
  j = lrand48()%4;
  FUP(k, j) empty.push_back(i);

  VIT(i, boards) VIT(j, boards[i]) if (boards[i][j] == "Fred") boards[i][j] = empty;
  VIT(i, bmps) VIT(j, bmps[i]) if (bmps[i][j] == "Fred") bmps[i][j] = empty;

  VIT(i, boards) {
    VIT(j, bmps[i]) {
      ss.clear(); 
      ss.str(bmps[i][j]);
      if (ss >> d) {
        pscores[j] += d;
        tplayed[j] ++;
      }
    }
  }


  VIT(i, pscores) {
    if (tplayed[i] == 0) perc.push_back(0); else perc.push_back(pscores[i]/tplayed[i]/top*100.0);
  }
  sperc = perc;
  sort(sperc.begin(), sperc.end());

  VIT(i, pscores) {
    j = lrand48()%5;
    printf("%*d %s / %s ", j, i+1, p[i*2].c_str(), p[i*2+1].c_str());
    j = lrand48()%10;
    printf("%*lg %*lg", j, pscores[i], j, perc[i]);
    if (perc[i] == sperc[np-1]) {
      if (format == 0) printf(" %.2lf(OA)", mp1);
      if (format == 1) printf(" (SA)%.2lf", mp1);
      if (format == 2) printf(" %.2lf mps A", mp1);
      if (winner) printf(" Winner");
    } else if (perc[i] == sperc[np-2]) {
      if (format == 0) printf(" %.2lf(O%c)", mp2, (lrand48()%2) ? 'A' : 'B');
      if (format == 1) printf(" (S%c)%.2lf", (lrand48()%2) ? 'A' : 'B', mp2);
      if (format == 2) printf(" %.2lf mps %c", mp2, (lrand48()%2) ? 'A' : 'B');
      if (second) printf(" Second");
    } else if (perc[i] == sperc[np-3]) {
      if (format == 0) printf(" %.2lf(O%c)", mp3, (lrand48()%2) ? 'A' : 'B');
      if (format == 1) printf(" (S%c)%.2lf", (lrand48()%2) ? 'A' : 'B', mp2);
      if (format == 2) printf(" %.2lf mps %c", mp3, (lrand48()%2) ? 'A' : 'B');
    }
    if (lrand48()%200 == 0) printf(" showed up late.");
    if (lrand48()%300 == 0) printf(" birthday!");
    printf("\n");
  }

  if (lrand48()%3 == 0) {
    printf("\n");
    FUP(i, np) printf(" %d", i+1);
    printf("\n");
    FUP(i, np) printf(" %s", empty.c_str());
    printf("\n");
  }
  
  VIT(i, boards) {
    printf("\n");
    printf("Board %d", i+1); 
    if (bfirst) {
      VIT(j, bmps[i]) { k = lrand48()%2+1; printf("%*s%s", k, " ", bmps[i][j].c_str()); } printf("\n");
      VIT(j, boards[i]) { k = lrand48()%2+1; printf("%*s%s", k, " ", boards[i][j].c_str()); } printf("\n");
    } else {
      VIT(j, boards[i]) { k = lrand48()%2+1; printf("%*s%s", k, " ", boards[i][j].c_str()); } printf("\n");
      VIT(j, bmps[i]) { k = lrand48()%2+1; printf("%*s%s", k, " ", bmps[i][j].c_str()); } printf("\n");
    }
  }    
}
  
