ALL = list_o_list_1 list_o_list_2 list_o_list_3 list_o_list_4 list_o_list_5 mytail_deque \
   mytail_list mytail_vector reverse_1 reverse_2 reverse_3 reverse_4 reverse_5  \
   make_bad_diamond

all: $(ALL)

clean:
	rm -f *.o $(ALL)

list_o_list_1: list_o_list_1.cpp
	g++ -o list_o_list_1 list_o_list_1.cpp

list_o_list_2: list_o_list_2.cpp
	g++ -o list_o_list_2 list_o_list_2.cpp

list_o_list_3: list_o_list_3.cpp
	g++ -o list_o_list_3 list_o_list_3.cpp

list_o_list_4: list_o_list_4.cpp
	g++ -o list_o_list_4 list_o_list_4.cpp

list_o_list_5: list_o_list_5.cpp
	g++ -o list_o_list_5 list_o_list_5.cpp

make_bad_diamond: make_bad_diamond.cpp
	g++ -o make_bad_diamond make_bad_diamond.cpp

mytail_deque: mytail_deque.cpp
	g++ -o mytail_deque mytail_deque.cpp

mytail_list: mytail_list.cpp
	g++ -o mytail_list mytail_list.cpp

mytail_vector: mytail_vector.cpp
	g++ -o mytail_vector mytail_vector.cpp

reverse_1: reverse_1.cpp
	g++ -o reverse_1 reverse_1.cpp

reverse_2: reverse_2.cpp
	g++ -o reverse_2 reverse_2.cpp

reverse_3: reverse_3.cpp
	g++ -o reverse_3 reverse_3.cpp

reverse_4: reverse_4.cpp
	g++ -o reverse_4 reverse_4.cpp

reverse_5: reverse_5.cpp
	g++ -o reverse_5 reverse_5.cpp

