#!/bin/sh 

dir=/home/plank/cs360/labs/lab5
ge="$dir/Gradescript-Examples"

if [ $# -ne 1 ]; then
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi

if [ "$1" -gt 0 -a "$1" -le 100 ]; then
  enum=`echo $1 | awk '{ printf "%03d\n", $1 }'`
else
  echo 'usage: gradescript problem_number (1-100)' >&2
  exit 1
fi
  
program=jtar

if [ ! -f $program ]; then
  echo "Problem $enum is incorrect."
  echo ""
  echo "Your program $program does not exist."
  exit 0
fi

chmod 0700 test-dir your-dir 2>/dev/null
chmod -R 0700 test-dir your-dir 2>/dev/null
rm -rf test-dir your-dir  tarfile
rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt tmp-$enum-correct-stdout.txt tmp-$enum-correct-stderr.txt 

scriptfile=$ge/$enum.script

call="sh $scriptfile > tmp-$enum-test-stdout.txt 2> tmp-$enum-test-stderr.txt"
sh $scriptfile > tmp-$enum-test-stdout.txt 2> tmp-$enum-test-stderr.txt

err=`wc tmp-$enum-test-stderr.txt | awk '{ print $1 }'`
out=`wc tmp-$enum-test-stdout.txt | awk '{ print $1 }'`

if [ $out != 0 -o $err != 0 ]; then
  echo "Problem $enum is incorrect."
  echo ""
  if [ $out != 0 ]; then
    echo "There is output on standard output, and there should not be."
  fi
  if [ $err != 0 ]; then
    echo "The checking program found an error between test-dir and your-dir.  Info on stderr."
  fi
  echo ""
  echo "TEST:"
  echo ""
  echo "sh -c 'chmod 0700 test-dir your-dir 2>/dev/null'"
  echo "sh -c 'chmod -R 0700 test-dir your-dir 2>/dev/null'"
  echo "rm -rf test-dir your-dir  tarfile"
  echo "rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt "
  echo "sh -c '$call'"
  echo ""
  echo "FILES:"
  echo ""
  echo "Your standard output is in tmp-$enum-test-stdout.txt."
  echo "Your standard error  is in tmp-$enum-test-stderr.txt."
  echo ""
  echo "The test directory is test-dir and your jtar produced your-dir"
  echo "Delete them with chmod -R 0700 test-dir your-dir; rm -rf test-dir your-dir."
else 
  echo "Problem $enum is correct."
  echo ""
  echo "TEST:"
  echo ""
  echo "sh -c 'chmod 0700 test-dir your-dir 2>/dev/null'"
  echo "sh -c 'chmod -R 0700 test-dir your-dir 2>/dev/null'"
  echo "rm -rf test-dir your-dir  tarfile"
  echo "rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt "
  echo "sh $scriptfile"
  echo ""
  chmod 0700 test-dir your-dir 2>/dev/null
  chmod -R 0700 test-dir your-dir 2>/dev/null
  rm -rf test-dir your-dir  tarfile
  rm -f tmp-$enum-test-stdout.txt tmp-$enum-test-stderr.txt 
fi
